{{ 
  config(
    alias='project_name_mappings',
    unique_key='dune_name'
    )  
}}

select 
  cast(dune_name as STRING) AS dune_name
  ,cast(mapped_name as STRING) AS mapped_name
FROM UNNEST(ARRAY<STRUCT<dune_name STRING,mapped_name STRING>> [STRUCT('lyra_v1',	'Lyra'),
STRUCT('Lyra V1', 'Lyra'),
STRUCT('aave_v3', 'Aave'),
STRUCT('perp_v2', 'Perpetual Protocol'),
STRUCT('synthetix_futures', 'Kwenta'),
STRUCT('zeroex', 'Zeroex (0x)' ),
STRUCT('uniswap_v3', 'Uniswap'),
STRUCT('Uniswap V3', 'Uniswap'),
STRUCT('oneinch', '1inch'),
STRUCT('pika_perp_v2', 'Pika Protocol'),
STRUCT('quixotic_v1', 'Quix'),
STRUCT('quixotic_v2', 'Quix'),
STRUCT('quixotic_v3', 'Quix'),
STRUCT('quixotic_v4', 'Quix'),
STRUCT('across_v2', 'Across'),
STRUCT('openocean_v2', 'OpenOcean'),
STRUCT('setprotocol_v2',	'Set Protocol'),
STRUCT('kromatikafinance', 'Kromatika'),
STRUCT('kratosdao', 'Kratos Dao'),
STRUCT('curvefi', 'Curve'),
STRUCT('pika_perp', 'Pika Protocol'),
STRUCT('dhedge_v2', 'Dhedge'),
STRUCT('bitbtc', 'Bitbtc Protocol'),
STRUCT('teleportr', 'Teleportr/ Warp Speed'),
STRUCT('balancer_v2', 'Beethoven X'),
STRUCT('stargate', 'Stargate Finance'),
STRUCT('quixotic_v5', 'Quix'),
STRUCT('lyra_avalon', 'Lyra'),
STRUCT('Lyra', 'Avalon Lyra'),
STRUCT('Unlock', 'Unlock Protocol'),
STRUCT('Xy Finance', 'XY Finance'),
STRUCT('Qidao', 'QiDao'),
STRUCT('Defisaver', 'Defi Saver'),
STRUCT('Layerzero', 'Layer Zero'),
STRUCT('Xtoken', 'xToken'),
STRUCT('Instadapp', 'InstaDapp'),
STRUCT('Lifi', 'LiFi'),
STRUCT('Optimistic Explorer', 'Optimistic Explorer - Get Started NFT'),
STRUCT('ironbank', 'Iron Bank'),
STRUCT('iron_bank', 'Iron Bank'),
STRUCT('bluesweep', 'BlueSweep'),
STRUCT('hidden_hand', 'Hidden Hand'),
STRUCT('quixotic', 'Quix'),
STRUCT('project galaxy', 'Galxe'),
STRUCT('project_galaxy', 'Galxe'),
STRUCT('Masoud_ecc', 'ECC Domains'),
STRUCT('opx_finance', 'OPX Finance'),
STRUCT('pooltogether_v3', 'PoolTogether'),
STRUCT('beethovenx', 'Beethoven X'),
STRUCT('openxswap', 'OpenXSwap'),
STRUCT('eccdomains', 'ECC Domains'),
STRUCT('2pi_network','2Pi Network'),
STRUCT('twopi_network','2Pi Network'),
STRUCT('acryptos', 'AcryptoS'),
STRUCT('woofi', 'WooFi'),
STRUCT('powerbomb_finance','Powerbomb Finance'),
STRUCT('powerbomb','Powerbomb Finance'),
STRUCT('lemma_finance','Lemma Finance'),
STRUCT('lemma','Lemma Finance'),
STRUCT('arrakis','Arrakis Finance'),
STRUCT('arrakis_finance','Arrakis Finance'),
STRUCT('collab_land_dao_pass', 'Collab Land'),
STRUCT('Llama', 'Llamapay'),
STRUCT('Perpetualprotocol','Perpetual Protocol'),
STRUCT('perp_hottub','Perpetual Protocol'),
STRUCT('Avalon Lyra', 'Lyra'),
STRUCT('avalon_lyra', 'Lyra')])