{{
  config(
        schema = 'chain_info',
        alias='chain_ids'
  )
}}



SELECT
`name` AS chain_name
,`chain` AS chain_shortname
,`nativeCurrency` AS native_currency_symbol
,`chainId` AS chain_id
,`networkId` AS network_id
,`infoURL` AS info_url
,`explorer` AS explorer
FROM UNNEST(ARRAY<STRUCT<`name` STRING,`chain` STRING,`nativeCurrency` STRING,`chainId` STRING,`networkId` STRING,`infoURL` STRING,`explorer` STRING>> [STRUCT('Ethereum Mainnet'	,'ETH'	,'ETH'	,'1'	,'1'	,'https://ethereum.org'	,'https://etherscan.io'),
STRUCT('Expanse Network'	,'EXP'	,'EXP'	,'2'	,'1'	,'https://expanse.tech'	,''),
STRUCT('Ropsten'	,'ETH'	,'ETH'	,'3'	,'3'	,'https://github.com/ethereum/ropsten'	,'https://ropsten.etherscan.io'),
STRUCT('Rinkeby'	,'ETH'	,'ETH'	,'4'	,'4'	,'https://www.rinkeby.io'	,'https://rinkeby.etherscan.io'),
STRUCT('Goerli'	,'ETH'	,'ETH'	,'5'	,'5'	,'https://goerli.net/#about'	,'https://goerli.etherscan.io'),
STRUCT('Ethereum Classic Testnet Kotti'	,'ETC'	,'KOT'	,'6'	,'6'	,'https://explorer.jade.builders/?network=kotti'	,''),
STRUCT('ThaiChain'	,'TCH'	,'TCH'	,'7'	,'7'	,'https://thaichain.io'	,''),
STRUCT('Ubiq'	,'UBQ'	,'UBQ'	,'8'	,'8'	,'https://ubiqsmart.com'	,'https://ubiqscan.io'),
STRUCT('Ubiq Network Testnet'	,'UBQ'	,'TUBQ'	,'9'	,'2'	,'https://ethersocial.org'	,''),
STRUCT('Optimism'	,'ETH'	,'ETH'	,'10'	,'10'	,'https://optimism.io'	,'https://optimistic.etherscan.io'),
STRUCT('Metadium Mainnet'	,'META'	,'META'	,'11'	,'11'	,'https://metadium.com'	,''),
STRUCT('Metadium Testnet'	,'META'	,'KAL'	,'12'	,'12'	,'https://metadium.com'	,''),
STRUCT('Diode Testnet Staging'	,'DIODE'	,'sDIODE'	,'13'	,'13'	,'https://diode.io/staging'	,''),
STRUCT('Flare Mainnet'	,'FLR'	,'FLR'	,'14'	,'14'	,'https://flare.xyz'	,'https://flare-explorer.flare.network'),
STRUCT('Diode Prenet'	,'DIODE'	,'DIODE'	,'15'	,'15'	,'https://diode.io/prenet'	,''),
STRUCT('Flare Testnet Coston'	,'FLR'	,'CFLR'	,'16'	,'16'	,'https://flare.xyz'	,'https://coston-explorer.flare.network'),
STRUCT('ThaiChain 2.0 ThaiFi'	,'TCH'	,'TFI'	,'17'	,'17'	,'https://exp.thaifi.com'	,''),
STRUCT('ThunderCore Testnet'	,'TST'	,'TST'	,'18'	,'18'	,'https://thundercore.com'	,'https://explorer-testnet.thundercore.com'),
STRUCT('Songbird Canary-Network'	,'SGB'	,'SGB'	,'19'	,'19'	,'https://flare.xyz'	,'https://songbird-explorer.flare.network'),
STRUCT('Elastos Smart Chain'	,'ETH'	,'ELA'	,'20'	,'20'	,'https://www.elastos.org/'	,'https://esc.elastos.io'),
STRUCT('Elastos Smart Chain Testnet'	,'ETH'	,'tELA'	,'21'	,'21'	,'https://www.elastos.org/'	,'https://esc-testnet.elastos.io'),
STRUCT('ELA-DID-Sidechain Mainnet'	,'ETH'	,'ELA'	,'22'	,'22'	,'https://www.elastos.org/'	,''),
STRUCT('ELA-DID-Sidechain Testnet'	,'ETH'	,'tELA'	,'23'	,'23'	,'https://elaeth.io/'	,''),
STRUCT('KardiaChain Mainnet'	,'KAI'	,'KAI'	,'24'	,'0'	,'https://kardiachain.io'	,''),
STRUCT('Cronos Mainnet Beta'	,'CRO'	,'CRO'	,'25'	,'25'	,'https://cronos.org/'	,'https://cronoscan.com'),
STRUCT('Genesis L1 testnet'	,'genesis'	,'L1test'	,'26'	,'26'	,'https://www.genesisl1.com'	,'https://testnet.genesisl1.org'),
STRUCT('ShibaChain'	,'SHIB'	,'SHIB'	,'27'	,'27'	,'https://www.shibachain.net'	,'https://exp.shibachain.net'),
STRUCT('Boba Network Rinkeby Testnet'	,'ETH'	,'ETH'	,'28'	,'28'	,'https://boba.network'	,'https://blockexplorer.rinkeby.boba.network'),
STRUCT('Genesis L1'	,'genesis'	,'L1'	,'29'	,'29'	,'https://www.genesisl1.com'	,'https://explorer.genesisl1.org'),
STRUCT('RSK Mainnet'	,'RSK'	,'RBTC'	,'30'	,'30'	,'https://rsk.co'	,'https://explorer.rsk.co'),
STRUCT('RSK Testnet'	,'RSK'	,'tRBTC'	,'31'	,'31'	,'https://rsk.co'	,'https://explorer.testnet.rsk.co'),
STRUCT('GoodData Testnet'	,'GooD'	,'GooD'	,'32'	,'32'	,'https://www.goodata.org'	,''),
STRUCT('GoodData Mainnet'	,'GooD'	,'GooD'	,'33'	,'33'	,'https://www.goodata.org'	,''),
STRUCT('Dithereum Testnet'	,'DTH'	,'DTH'	,'34'	,'34'	,'https://dithereum.org'	,''),
STRUCT('TBWG Chain'	,'TBWG'	,'TBG'	,'35'	,'35'	,'https://tbwg.io'	,''),
STRUCT('Dxchain Mainnet'	,'Dxchain'	,'DX'	,'36'	,'36'	,'https://www.dxchain.com/'	,'https://dxscan.io'),
STRUCT('SeedCoin-Network'	,'SeedCoin-Network'	,'SEED'	,'37'	,'37'	,'https://www.seedcoin.network/'	,''),
STRUCT('Valorbit'	,'VAL'	,'VAL'	,'38'	,'38'	,'https://valorbit.com'	,''),
STRUCT('Telos EVM Mainnet'	,'TLOS'	,'TLOS'	,'40'	,'40'	,'https://telos.net'	,'https://teloscan.io'),
STRUCT('Telos EVM Testnet'	,'TLOS'	,'TLOS'	,'41'	,'41'	,'https://telos.net'	,''),
STRUCT('Kovan'	,'ETH'	,'ETH'	,'42'	,'42'	,'https://kovan-testnet.github.io/website'	,'https://kovan.etherscan.io'),
STRUCT('Darwinia Pangolin Testnet'	,'pangolin'	,'PRING'	,'43'	,'43'	,'https://darwinia.network/'	,'https://pangolin.subscan.io'),
STRUCT('Darwinia Crab Network'	,'crab'	,'CRAB'	,'44'	,'44'	,'https://crab.network/'	,'https://crab.subscan.io'),
STRUCT('Darwinia Pangoro Testnet'	,'pangoro'	,'ORING'	,'45'	,'45'	,'https://darwinia.network/'	,'https://pangoro.subscan.io'),
STRUCT('Darwinia Network'	,'darwinia'	,'RING'	,'46'	,'46'	,'https://darwinia.network/'	,'https://darwinia.subscan.io'),
STRUCT('Ennothem Mainnet Proterozoic'	,'ETMP'	,'ETMP'	,'48'	,'48'	,'https://etm.network'	,'https://etmscan.network'),
STRUCT('Ennothem Testnet Pioneer'	,'ETMP'	,'ETMP'	,'49'	,'49'	,'https://etm.network'	,'https://pioneer.etmscan.network'),
STRUCT('XinFin XDC Network'	,'XDC'	,'XDC'	,'50'	,'50'	,'https://xinfin.org'	,'https://xdcscan.io'),
STRUCT('XDC Apothem Network'	,'XDC'	,'TXDC'	,'51'	,'51'	,'https://xinfin.org'	,'https://apothem.xinfinscan.com'),
STRUCT('CoinEx Smart Chain Mainnet'	,'CSC'	,'cet'	,'52'	,'52'	,'https://www.coinex.org/'	,'https://www.coinex.net'),
STRUCT('CoinEx Smart Chain Testnet'	,'CSC'	,'cett'	,'53'	,'53'	,'https://www.coinex.org/'	,'https://testnet.coinex.net'),
STRUCT('Openpiece Mainnet'	,'OPENPIECE'	,'BELLY'	,'54'	,'54'	,'https://cryptopiece.online'	,'https://bellyscan.com'),
STRUCT('Zyx Mainnet'	,'ZYX'	,'ZYX'	,'55'	,'55'	,'https://zyx.network/'	,'https://zyxscan.com'),
STRUCT('Binance Smart Chain Mainnet'	,'BSC'	,'BNB'	,'56'	,'56'	,'https://www.binance.org'	,'https://bscscan.com'),
STRUCT('Syscoin Mainnet'	,'SYS'	,'SYS'	,'57'	,'57'	,'https://www.syscoin.org'	,'https://explorer.syscoin.org'),
STRUCT('Ontology Mainnet'	,'Ontology'	,'ONG'	,'58'	,'58'	,'https://ont.io/'	,'https://explorer.ont.io'),
STRUCT('EOS Mainnet'	,'EOS'	,'EOS'	,'59'	,'59'	,'https://eoscommunity.org/'	,'https://bloks.eosargentina.io'),
STRUCT('GoChain'	,'GO'	,'GO'	,'60'	,'60'	,'https://gochain.io'	,'https://explorer.gochain.io'),
STRUCT('Ethereum Classic Mainnet'	,'ETC'	,'ETC'	,'61'	,'1'	,'https://ethereumclassic.org'	,'https://blockscout.com/etc/mainnet'),
STRUCT('Ethereum Classic Testnet Morden'	,'ETC'	,'TETC'	,'62'	,'2'	,'https://ethereumclassic.org'	,''),
STRUCT('Ethereum Classic Testnet Mordor'	,'ETC'	,'METC'	,'63'	,'7'	,'https://github.com/eth-classic/mordor/'	,''),
STRUCT('Ellaism'	,'ELLA'	,'ELLA'	,'64'	,'64'	,'https://ellaism.org'	,''),
STRUCT('OKExChain Testnet'	,'okexchain'	,'OKT'	,'65'	,'65'	,'https://www.okex.com/okexchain'	,'https://www.oklink.com/okexchain-test'),
STRUCT('OKXChain Mainnet'	,'okxchain'	,'OKT'	,'66'	,'66'	,'https://www.okex.com/okc'	,'https://www.oklink.com/en/okc'),
STRUCT('DBChain Testnet'	,'DBM'	,'DBM'	,'67'	,'67'	,'http://test.dbmbp.com'	,''),
STRUCT('SoterOne Mainnet'	,'SOTER'	,'SOTER'	,'68'	,'68'	,'https://www.soterone.com'	,''),
STRUCT('Optimism Kovan'	,'ETH'	,'ETH'	,'69'	,'69'	,'https://optimism.io'	,'https://kovan-optimistic.etherscan.io'),
STRUCT('Hoo Smart Chain'	,'HSC'	,'HOO'	,'70'	,'70'	,'https://www.hoosmartchain.com'	,'https://www.hooscan.com'),
STRUCT('Conflux eSpace (Testnet)'	,'Conflux'	,'CFX'	,'71'	,'71'	,'https://confluxnetwork.org'	,'https://evmtestnet.confluxscan.net'),
STRUCT('DxChain Testnet'	,'DxChain'	,'DX'	,'72'	,'72'	,'https://testnet.dxscan.io/'	,''),
STRUCT('FNCY'	,'FNCY'	,'FNCY'	,'73'	,'73'	,'https://fncyscan.fncy.world'	,'https://fncyscan.fncy.world'),
STRUCT('IDChain Mainnet'	,'IDChain'	,'EIDI'	,'74'	,'74'	,'https://idchain.one/begin/'	,'https://explorer.idchain.one'),
STRUCT('Mix'	,'MIX'	,'MIX'	,'76'	,'76'	,'https://mix-blockchain.org'	,''),
STRUCT('POA Network Sokol'	,'POA'	,'SPOA'	,'77'	,'77'	,'https://poa.network'	,'https://blockscout.com/poa/sokol'),
STRUCT('PrimusChain mainnet'	,'PC'	,'PETH'	,'78'	,'78'	,'https://primusmoney.com'	,''),
STRUCT('Zenith Mainnet'	,'Zenith'	,'ZENITH'	,'79'	,'79'	,'https://www.zenithchain.co/'	,'https://scan.zenithchain.co'),
STRUCT('GeneChain'	,'GeneChain'	,'RNA'	,'80'	,'80'	,'https://scan.genechain.io/'	,'https://scan.genechain.io'),
STRUCT('Zenith Testnet (Vilnius)'	,'Zenith'	,'VIL'	,'81'	,'81'	,'https://www.zenithchain.co/'	,'https://vilnius.scan.zenithchain.co'),
STRUCT('Meter Mainnet'	,'METER'	,'MTR'	,'82'	,'82'	,'https://www.meter.io'	,'https://scan.meter.io'),
STRUCT('Meter Testnet'	,'METER Testnet'	,'MTR'	,'83'	,'83'	,'https://www.meter.io'	,'https://scan-warringstakes.meter.io'),
STRUCT('GateChain Testnet'	,'GTTEST'	,'GT'	,'85'	,'85'	,'https://www.gatechain.io'	,'https://www.gatescan.org/testnet'),
STRUCT('GateChain Mainnet'	,'GT'	,'GT'	,'86'	,'86'	,'https://www.gatechain.io'	,'https://www.gatescan.org'),
STRUCT('Nova Network'	,'NNW'	,'SNT'	,'87'	,'87'	,'https://novanetwork.io'	,'https://explorer.novanetwork.io'),
STRUCT('TomoChain'	,'TOMO'	,'TOMO'	,'88'	,'88'	,'https://tomochain.com'	,''),
STRUCT('TomoChain Testnet'	,'TOMO'	,'TOMO'	,'89'	,'89'	,'https://tomochain.com'	,''),
STRUCT('Garizon Stage0'	,'GAR'	,'GAR'	,'90'	,'90'	,'https://garizon.com'	,'https://explorer.garizon.com'),
STRUCT('Garizon Stage1'	,'GAR'	,'GAR'	,'91'	,'91'	,'https://garizon.com'	,'https://explorer.garizon.com'),
STRUCT('Garizon Stage2'	,'GAR'	,'GAR'	,'92'	,'92'	,'https://garizon.com'	,'https://explorer.garizon.com'),
STRUCT('Garizon Stage3'	,'GAR'	,'GAR'	,'93'	,'93'	,'https://garizon.com'	,'https://explorer.garizon.com'),
STRUCT('CryptoKylin Testnet'	,'EOS'	,'EOS'	,'95'	,'95'	,'https://www.cryptokylin.io/'	,'https://kylin.eosargentina.io'),
STRUCT('NEXT Smart Chain'	,'NSC'	,'NEXT'	,'96'	,'96'	,'https://www.nextsmartchain.com/'	,'https://explorer.nextsmartchain.com'),
STRUCT('Binance Smart Chain Testnet'	,'BSC'	,'tBNB'	,'97'	,'97'	,'https://testnet.binance.org/'	,'https://testnet.bscscan.com'),
STRUCT('POA Network Core'	,'POA'	,'POA'	,'99'	,'99'	,'https://poa.network'	,'https://blockscout.com/poa/core'),
STRUCT('Gnosis'	,'GNO'	,'xDAI'	,'100'	,'100'	,'https://docs.gnosischain.com'	,'https://gnosisscan.io'),
STRUCT('EtherInc'	,'ETI'	,'ETI'	,'101'	,'1'	,'https://einc.io'	,''),
STRUCT('Web3Games Testnet'	,'Web3Games'	,'W3G'	,'102'	,'102'	,'https://web3games.org/'	,''),
STRUCT('Kaiba Lightning Chain Testnet'	,'tKLC'	,'tKAIBA'	,'104'	,'104'	,'https://kaibadefi.com'	,'https://kaibascan.io'),
STRUCT('Web3Games Devnet'	,'Web3Games'	,'W3G'	,'105'	,'105'	,'https://web3games.org/'	,'https://explorer-devnet.web3games.org'),
STRUCT('Velas EVM Mainnet'	,'Velas'	,'VLX'	,'106'	,'106'	,'https://velas.com'	,'https://evmexplorer.velas.com'),
STRUCT('Nebula Testnet'	,'NTN'	,'NBX'	,'107'	,'107'	,'https://novanetwork.io'	,'https://explorer.novanetwork.io'),
STRUCT('ThunderCore Mainnet'	,'TT'	,'TT'	,'108'	,'108'	,'https://thundercore.com'	,'https://viewblock.io/thundercore'),
STRUCT('Proton Testnet'	,'XPR'	,'XPR'	,'110'	,'110'	,'https://protonchain.com'	,''),
STRUCT('EtherLite Chain'	,'ETL'	,'ETL'	,'111'	,'111'	,'https://etherlite.org'	,''),
STRUCT('Dehvo'	,'Dehvo'	,'Deh'	,'113'	,'113'	,'https://dehvo.com'	,'https://explorer.dehvo.com'),
STRUCT('DeBank Testnet'	,'DeBank'	,'ETH'	,'115'	,'115'	,'https://debank.com'	,''),
STRUCT('DeBank Mainnet'	,'DeBank'	,'ETH'	,'116'	,'116'	,'https://debank.com'	,''),
STRUCT('Fuse Mainnet'	,'FUSE'	,'FUSE'	,'122'	,'122'	,'https://fuse.io/'	,''),
STRUCT('Fuse Sparknet'	,'fuse'	,'SPARK'	,'123'	,'123'	,'https://docs.fuse.io/general/fuse-network-blockchain/fuse-testnet'	,''),
STRUCT('Decentralized Web Mainnet'	,'DWU'	,'DWU'	,'124'	,'124'	,'https://decentralized-web.tech/dw_chain.php'	,''),
STRUCT('OYchain Testnet'	,'OYchain'	,'OY'	,'125'	,'125'	,'https://www.oychain.io'	,'https://explorer.testnet.oychain.io'),
STRUCT('OYchain Mainnet'	,'OYchain'	,'OY'	,'126'	,'126'	,'https://www.oychain.io'	,'https://explorer.oychain.io'),
STRUCT('Factory 127 Mainnet'	,'FETH'	,'FETH'	,'127'	,'127'	,'https://www.factory127.com'	,''),
STRUCT('Huobi ECO Chain Mainnet'	,'Heco'	,'HT'	,'128'	,'128'	,'https://www.hecochain.com'	,'https://hecoinfo.com'),
STRUCT('Alyx Chain Testnet'	,'Alyx Chain Testnet'	,'ALYX'	,'135'	,'135'	,'https://www.alyxchain.com'	,'https://testnet.alyxscan.com'),
STRUCT('Polygon Mainnet'	,'Polygon'	,'MATIC'	,'137'	,'137'	,'https://polygon.technology/'	,'https://polygonscan.com'),
STRUCT('Openpiece Testnet'	,'OPENPIECE'	,'BELLY'	,'141'	,'141'	,'https://cryptopiece.online'	,'https://testnet.bellyscan.com'),
STRUCT('DAX CHAIN'	,'DAX'	,'DAX'	,'142'	,'142'	,'https://prodax.io/'	,''),
STRUCT('PHI Network v2'	,'PHI'	,'Φ'	,'144'	,'144'	,'https://phi.network'	,'https://phiscan.com'),
STRUCT('Lightstreams Testnet'	,'PHT'	,'PHT'	,'162'	,'162'	,'https://explorer.sirius.lightstreams.io'	,''),
STRUCT('Lightstreams Mainnet'	,'PHT'	,'PHT'	,'163'	,'163'	,'https://explorer.lightstreams.io'	,''),
STRUCT('AIOZ Network'	,'AIOZ'	,'AIOZ'	,'168'	,'168'	,'https://aioz.network'	,'https://explorer.aioz.network'),
STRUCT('HOO Smart Chain Testnet'	,'ETH'	,'HOO'	,'170'	,'170'	,'https://www.hoosmartchain.com'	,''),
STRUCT('Latam-Blockchain Resil Testnet'	,'Resil'	,'usd'	,'172'	,'172'	,'https://latam-blockchain.com'	,''),
STRUCT('AME Chain Mainnet'	,'AME'	,'AME'	,'180'	,'180'	,'https://amechain.io/'	,'https://amescan.io'),
STRUCT('Seele Mainnet'	,'Seele'	,'Seele'	,'186'	,'186'	,'https://seelen.pro/'	,'https://seeleview.net'),
STRUCT('BMC Mainnet'	,'BMC'	,'BTM'	,'188'	,'188'	,'https://bmc.bytom.io/'	,'https://bmc.blockmeta.com'),
STRUCT('BMC Testnet'	,'BMC'	,'BTM'	,'189'	,'189'	,'https://bmc.bytom.io/'	,'https://bmctestnet.blockmeta.com'),
STRUCT('Crypto Emergency'	,'CEM'	,'CEM'	,'193'	,'193'	,'https://cemblockchain.com/'	,'https://cemscan.com'),
STRUCT('BitTorrent Chain Mainnet'	,'BTTC'	,'BTT'	,'199'	,'199'	,'https://bittorrentchain.io/'	,'https://scan.bittorrentchain.io'),
STRUCT('Arbitrum on xDai'	,'AOX'	,'xDAI'	,'200'	,'200'	,'https://xdaichain.com'	,'https://blockscout.com/xdai/arbitrum'),
STRUCT('MOAC testnet'	,'MOAC'	,'mc'	,'201'	,'201'	,'https://moac.io'	,'https://testnet.moac.io'),
STRUCT('Freight Trust Network'	,'EDI'	,'0xF'	,'211'	,'0'	,'https://freighttrust.com'	,''),
STRUCT('MAP Makalu'	,'MAP'	,'MAP'	,'212'	,'212'	,'https://maplabs.io'	,'https://testnet.mapscan.io'),
STRUCT('SoterOne Mainnet old'	,'SOTER'	,'SOTER'	,'218'	,'218'	,'https://www.soterone.com'	,''),
STRUCT('Permission'	,'ASK'	,'ASK'	,'222'	,'2221'	,'https://permission.io/'	,''),
STRUCT('LACHAIN Mainnet'	,'LA'	,'LA'	,'225'	,'225'	,'https://lachain.io'	,'https://scan.lachain.io'),
STRUCT('LACHAIN Testnet'	,'TLA'	,'TLA'	,'226'	,'226'	,'https://lachain.io'	,'https://scan-test.lachain.io'),
STRUCT('Energy Web Chain'	,'Energy Web Chain'	,'EWT'	,'246'	,'246'	,'https://energyweb.org'	,'https://explorer.energyweb.org'),
STRUCT('Oasys Mainnet'	,'Oasys'	,'OAS'	,'248'	,'248'	,'https://oasys.games'	,'https://explorer.oasys.games'),
STRUCT('Fantom Opera'	,'FTM'	,'FTM'	,'250'	,'250'	,'https://fantom.foundation'	,'https://ftmscan.com'),
STRUCT('Huobi ECO Chain Testnet'	,'Heco'	,'htt'	,'256'	,'256'	,'https://testnet.hecoinfo.com'	,''),
STRUCT('Setheum'	,'Setheum'	,'SETM'	,'258'	,'258'	,'https://setheum.xyz'	,''),
STRUCT('SUR Blockchain Network'	,'SUR'	,'SRN'	,'262'	,'1'	,'https://surnet.org'	,'https://explorer.surnet.org'),
STRUCT('High Performance Blockchain'	,'HPB'	,'HPB'	,'269'	,'269'	,'https://hpb.io'	,'https://hscan.org'),
STRUCT('zkSync alpha testnet'	,'ETH'	,'ETH'	,'280'	,'280'	,'https://v2-docs.zksync.io/'	,'https://zksync2-testnet.zkscan.io'),
STRUCT('Boba Network'	,'ETH'	,'ETH'	,'288'	,'288'	,'https://boba.network'	,'https://bobascan.com'),
STRUCT('Optimism on Gnosis'	,'OGC'	,'xDAI'	,'300'	,'300'	,'https://www.xdaichain.com/for-developers/optimism-optimistic-rollups-on-gc'	,'https://blockscout.com/xdai/optimism'),
STRUCT('Filecoin - Mainnet'	,'FIL'	,'FIL'	,'314'	,'314'	,'https://filecoin.io'	,'https://filfox.info/en'),
STRUCT('KCC Mainnet'	,'KCC'	,'KCS'	,'321'	,'321'	,'https://kcc.io'	,'https://explorer.kcc.io/en'),
STRUCT('KCC Testnet'	,'KCC'	,'tKCS'	,'322'	,'322'	,'https://scan-testnet.kcc.network'	,'https://scan-testnet.kcc.network'),
STRUCT('Web3Q Mainnet'	,'Web3Q'	,'W3Q'	,'333'	,'333'	,'https://web3q.io/home.w3q/'	,'https://explorer.mainnet.web3q.io'),
STRUCT('DFK Chain Test'	,'DFK'	,'JEWEL'	,'335'	,'335'	,'https://defikingdoms.com'	,'https://explorer-test.dfkchain.com'),
STRUCT('Shiden'	,'SDN'	,'SDN'	,'336'	,'336'	,'https://shiden.astar.network/'	,'https://shiden.subscan.io'),
STRUCT('Cronos Testnet'	,'CRO'	,'TCRO'	,'338'	,'338'	,'https://cronos.org'	,'https://testnet.cronoscan.com'),
STRUCT('Theta Mainnet'	,'Theta'	,'TFUEL'	,'361'	,'361'	,'https://www.thetatoken.org/'	,'https://explorer.thetatoken.org'),
STRUCT('Theta Sapphire Testnet'	,'Theta'	,'TFUEL'	,'363'	,'363'	,'https://www.thetatoken.org/'	,'https://guardian-testnet-sapphire-explorer.thetatoken.org'),
STRUCT('Theta Amber Testnet'	,'Theta'	,'TFUEL'	,'364'	,'364'	,'https://www.thetatoken.org/'	,'https://guardian-testnet-amber-explorer.thetatoken.org'),
STRUCT('Theta Testnet'	,'Theta'	,'TFUEL'	,'365'	,'365'	,'https://www.thetatoken.org/'	,'https://testnet-explorer.thetatoken.org'),
STRUCT('PulseChain Mainnet'	,'PLS'	,'PLS'	,'369'	,'369'	,'https://pulsechain.com/'	,''),
STRUCT('Lisinski'	,'CRO'	,'LISINS'	,'385'	,'385'	,'https://lisinski.online'	,''),
STRUCT('HyperonChain TestNet'	,'HPN'	,'HPN'	,'400'	,'400'	,'https://docs.hyperonchain.com'	,'https://testnet.hyperonchain.com'),
STRUCT('SX Network Mainnet'	,'SX'	,'SX'	,'416'	,'416'	,'https://www.sx.technology'	,'https://explorer.sx.technology'),
STRUCT('Optimism Goerli Testnet'	,'ETH'	,'ETH'	,'420'	,'420'	,'https://optimism.io'	,''),
STRUCT('Rupaya'	,'RUPX'	,'RUPX'	,'499'	,'499'	,'https://www.rupx.io'	,''),
STRUCT('FLOAT64-A Chain Mainnet'	,'AAC'	,'AAC'	,'512'	,'512'	,'https://www.acuteangle.com/'	,'https://scan.acuteangle.com'),
STRUCT('FLOAT64-A Chain Testnet'	,'AAC'	,'AAC'	,'513'	,'513'	,'https://www.acuteangle.com/'	,'https://scan-testnet.acuteangle.com'),
STRUCT('Gear Zero Network Mainnet'	,'GearZero'	,'GZN'	,'516'	,'516'	,'https://token.gearzero.ca/mainnet'	,''),
STRUCT('XT Smart Chain Mainnet'	,'XSC'	,'XT'	,'520'	,'1024'	,'https://xsc.pub/'	,'https://xscscan.pub'),
STRUCT('F(x)Core Mainnet Network'	,'Fxcore'	,'FX'	,'530'	,'530'	,'https://functionx.io/'	,'https://fx-evm.functionx.io'),
STRUCT('Candle'	,'Candle'	,'CNDL'	,'534'	,'534'	,'https://candlelabs.org/'	,'https://candleexplorer.com'),
STRUCT('Vela1 Chain Mainnet'	,'VELA1'	,'CLASS'	,'555'	,'555'	,'https://velaverse.io'	,'https://exp.velaverse.io'),
STRUCT('Tao Network'	,'TAO'	,'TAO'	,'558'	,'558'	,'https://tao.network'	,''),
STRUCT('Dogechain Testnet'	,'DC'	,'DOGE'	,'568'	,'568'	,'https://dogechain.dog'	,'https://explorer-testnet.dogechain.dog'),
STRUCT('Metis Stardust Testnet'	,'ETH'	,'METIS'	,'588'	,'588'	,'https://www.metis.io'	,'https://stardust-explorer.metis.io'),
STRUCT('Astar'	,'ASTR'	,'ASTR'	,'592'	,'592'	,'https://astar.network/'	,'https://astar.subscan.io'),
STRUCT('Acala Mandala Testnet'	,'mACA'	,'mACA'	,'595'	,'595'	,'https://acala.network'	,''),
STRUCT('Karura Network Testnet'	,'KAR'	,'KAR'	,'596'	,'596'	,'https://karura.network'	,''),
STRUCT('Acala Network Testnet'	,'ACA'	,'ACA'	,'597'	,'597'	,'https://acala.network'	,''),
STRUCT('Metis Goerli Testnet'	,'ETH'	,'METIS'	,'599'	,'599'	,'https://www.metis.io'	,'https://goerli.explorer.metisdevops.link'),
STRUCT('Meshnyan testnet'	,'MeshTestChain'	,'MESHT'	,'600'	,'600'	,''	,''),
STRUCT('SX Network Testnet'	,'SX'	,'SX'	,'647'	,'647'	,'https://www.sx.technology'	,'https://explorer.toronto.sx.technology'),
STRUCT('Pixie Chain Testnet'	,'PixieChain'	,'PCTT'	,'666'	,'666'	,'https://scan-testnet.chain.pixie.xyz'	,''),
STRUCT('Karura Network'	,'KAR'	,'KAR'	,'686'	,'686'	,'https://karura.network'	,''),
STRUCT('Star Social Testnet'	,'SNS'	,'SNS'	,'700'	,'700'	,'https://info.avastar.cc'	,'https://avastar.info'),
STRUCT('BlockChain Station Mainnet'	,'BCS'	,'BCS'	,'707'	,'707'	,'https://blockchainstation.io'	,'https://explorer.bcsdev.io'),
STRUCT('BlockChain Station Testnet'	,'BCS'	,'tBCS'	,'708'	,'708'	,'https://blockchainstation.io'	,'https://testnet.bcsdev.io'),
STRUCT('Lycan Chain'	,'LYC'	,'LYC'	,'721'	,'721'	,'https://lycanchain.com'	,'https://explorer.lycanchain.com'),
STRUCT('QL1'	,'QOM'	,'QOM'	,'766'	,'766'	,'https://qom.one'	,'https://mainnet.qom.one'),
STRUCT('OpenChain Testnet'	,'OpenChain Testnet'	,'TOPC'	,'776'	,'776'	,'https://testnet.openchain.info/'	,'https://testnet.openchain.info'),
STRUCT('cheapETH'	,'cheapETH'	,'cTH'	,'777'	,'777'	,'https://cheapeth.org/'	,''),
STRUCT('Acala Network'	,'ACA'	,'ACA'	,'787'	,'787'	,'https://acala.network'	,''),
STRUCT('Aerochain Testnet'	,'Aerochain'	,'TAero'	,'788'	,'788'	,'https://aerochaincoin.org/'	,'https://testnet.aeroscan.id'),
STRUCT('Haic'	,'Haic'	,'HAIC'	,'803'	,'803'	,'https://www.haichain.io/'	,''),
STRUCT('Portal Fantasy Chain Test'	,'PF'	,'PFT'	,'808'	,'808'	,'https://portalfantasy.io'	,''),
STRUCT('Qitmeer'	,'MEER'	,'MEER'	,'813'	,'813'	,'https://github.com/Qitmeer'	,'https://evm.meerscan.com'),
STRUCT('Callisto Mainnet'	,'CLO'	,'CLO'	,'820'	,'1'	,'https://callisto.network'	,''),
STRUCT('Callisto Testnet Deprecated'	,'CLO'	,'TCLO'	,'821'	,'2'	,'https://callisto.network'	,''),
STRUCT('Ambros Chain Mainnet'	,'ambroschain'	,'AMBROS'	,'880'	,'880'	,'https://ambros.network'	,'https://ambrosscan.com'),
STRUCT('Wanchain'	,'WAN'	,'WAN'	,'888'	,'888'	,'https://www.wanscan.org'	,''),
STRUCT('Garizon Testnet Stage0'	,'GAR'	,'GAR'	,'900'	,'900'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com'),
STRUCT('Garizon Testnet Stage1'	,'GAR'	,'GAR'	,'901'	,'901'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com'),
STRUCT('Garizon Testnet Stage2'	,'GAR'	,'GAR'	,'902'	,'902'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com'),
STRUCT('Garizon Testnet Stage3'	,'GAR'	,'GAR'	,'903'	,'903'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com'),
STRUCT('Portal Fantasy Chain'	,'PF'	,'PFT'	,'909'	,'909'	,'https://portalfantasy.io'	,''),
STRUCT('PulseChain Testnet'	,'tPLS'	,'tPLS'	,'940'	,'940'	,'https://pulsechain.com/'	,''),
STRUCT('PulseChain Testnet v2b'	,'t2bPLS'	,'tPLS'	,'941'	,'941'	,'https://pulsechain.com/'	,''),
STRUCT('PulseChain Testnet v3'	,'t3PLS'	,'tPLS'	,'942'	,'942'	,'https://pulsechain.com/'	,''),
STRUCT('CCN'	,'CCN'	,'CCN'	,'970'	,'970'	,'https://computecoin.com/'	,''),
STRUCT('CCN Beta'	,'CCN Beta'	,'CCN'	,'971'	,'971'	,'https://computecoin.com/'	,''),
STRUCT('Nepal Blockchain Network'	,'YETI'	,'YETI'	,'977'	,'977'	,'https://nepalblockchain.network'	,''),
STRUCT('TOP Mainnet EVM'	,'TOP'	,'ETH'	,'980'	,'0'	,'https://www.topnetwork.org/'	,'https://www.topscan.io'),
STRUCT('Memo Smart Chain Mainnet'	,'MEMO'	,'CMEMO'	,'985'	,'985'	,'www.memolabs.org'	,'https://scan.metamemo.one:8080'),
STRUCT('TOP Mainnet'	,'TOP'	,'TOP'	,'989'	,'0'	,'https://www.topnetwork.org/'	,'https://www.topscan.io'),
STRUCT('Lucky Network'	,'LN'	,'L99'	,'998'	,'998'	,'https://luckynetwork.org'	,'https://explorer.luckynetwork.org'),
STRUCT('Wanchain Testnet'	,'WAN'	,'WAN'	,'999'	,'999'	,'https://testnet.wanscan.org'	,''),
STRUCT('GTON Mainnet'	,'GTON'	,'GCD'	,'1000'	,'1000'	,'https://gton.capital'	,'https://explorer.gton.network'),
STRUCT('Klaytn Testnet Baobab'	,'KLAY'	,'KLAY'	,'1001'	,'1001'	,'https://www.klaytn.com/'	,''),
STRUCT('Newton Testnet'	,'NEW'	,'NEW'	,'1007'	,'1007'	,'https://www.newtonproject.org/'	,''),
STRUCT('Eurus Mainnet'	,'EUN'	,'EUN'	,'1008'	,'1008'	,'https://eurus.network'	,'https://explorer.eurus.network'),
STRUCT('Evrice Network'	,'EVC'	,'EVC'	,'1010'	,'1010'	,'https://evrice.com'	,''),
STRUCT('Newton'	,'NEW'	,'NEW'	,'1012'	,'1012'	,'https://www.newtonproject.org/'	,''),
STRUCT('Sakura'	,'Sakura'	,'SKU'	,'1022'	,'1022'	,'https://clover.finance/sakura'	,''),
STRUCT('Clover Testnet'	,'Clover'	,'CLV'	,'1023'	,'1023'	,'https://clover.finance'	,''),
STRUCT('CLV Parachain'	,'CLV'	,'CLV'	,'1024'	,'1024'	,'https://clv.org'	,''),
STRUCT('BitTorrent Chain Testnet'	,'BTTC'	,'BTT'	,'1028'	,'1028'	,'https://bittorrentchain.io/'	,'https://testscan.bittorrentchain.io'),
STRUCT('Conflux eSpace'	,'Conflux'	,'CFX'	,'1030'	,'1030'	,'https://confluxnetwork.org'	,'https://evm.confluxscan.net'),
STRUCT('Bronos Testnet'	,'Bronos'	,'tBRO'	,'1038'	,'1038'	,'https://bronos.org'	,'https://tbroscan.bronos.org'),
STRUCT('Bronos Mainnet'	,'Bronos'	,'BRO'	,'1039'	,'1039'	,'https://bronos.org'	,'https://broscan.bronos.org'),
STRUCT('Metis Andromeda Mainnet'	,'ETH'	,'METIS'	,'1088'	,'1088'	,'https://www.metis.io'	,'https://andromeda-explorer.metis.io'),
STRUCT('MOAC mainnet'	,'MOAC'	,'mc'	,'1099'	,'1099'	,'https://moac.io'	,'https://explorer.moac.io'),
STRUCT('WEMIX3.0 Mainnet'	,'WEMIX'	,'WEMIX'	,'1111'	,'1111'	,'https://wemix.com'	,'https://explorer.wemix.com'),
STRUCT('WEMIX3.0 Testnet'	,'TWEMIX'	,'tWEMIX'	,'1112'	,'1112'	,'https://wemix.com'	,'https://microscope.test.wemix.com'),
STRUCT('DeFiChain EVM Network Mainnet'	,'defichain-evm'	,'DFI'	,'1130'	,'1130'	,'https://meta.defichain.com/'	,''),
STRUCT('DeFiChain EVM Network Testnet'	,'defichain-evm-testnet'	,'DFI'	,'1131'	,'1131'	,'https://meta.defichain.com/'	,''),
STRUCT('MathChain'	,'MATH'	,'MATH'	,'1139'	,'1139'	,'https://mathchain.org'	,''),
STRUCT('MathChain Testnet'	,'MATH'	,'MATH'	,'1140'	,'1140'	,'https://mathchain.org'	,''),
STRUCT('Iora Chain'	,'IORA'	,'IORA'	,'1197'	,'1197'	,'https://iorachain.com'	,'https://explorer.iorachain.com'),
STRUCT('Evanesco Testnet'	,'Evanesco Testnet'	,'AVIS'	,'1201'	,'1201'	,'https://evanesco.org/'	,''),
STRUCT('World Trade Technical Chain Mainnet'	,'WTT'	,'WTT'	,'1202'	,'2048'	,'http://www.cadaut.com'	,'https://explorer.cadaut.com'),
STRUCT('Popcateum Mainnet'	,'POPCATEUM'	,'POP'	,'1213'	,'1213'	,'https://popcateum.org'	,'https://explorer.popcateum.org'),
STRUCT('EnterChain Mainnet'	,'ENTER'	,'ENTER'	,'1214'	,'1214'	,'https://entercoin.net'	,'https://explorer.entercoin.net'),
STRUCT('Ultron Testnet'	,'Ultron'	,'ULX'	,'1230'	,'1230'	,'https://ultron.foundation'	,'https://explorer.ultron-dev.io'),
STRUCT('Ultron Mainnet'	,'Ultron'	,'ULX'	,'1231'	,'1231'	,'https://ultron.foundation'	,'https://ulxscan.com'),
STRUCT('Step Network'	,'STEP'	,'FITFI'	,'1234'	,'1234'	,'https://step.network'	,'https://stepscan.io'),
STRUCT('OM Platform Mainnet'	,'omplatform'	,'OM'	,'1246'	,'1246'	,'https://omplatform.com/'	,'https://omscan.omplatform.com'),
STRUCT('HALO Mainnet'	,'HALO'	,'HO'	,'1280'	,'1280'	,'https://halo.land/#/'	,'https://browser.halo.land'),
STRUCT('Moonbeam'	,'MOON'	,'GLMR'	,'1284'	,'1284'	,'https://moonbeam.network/networks/moonbeam/'	,'https://moonbeam.moonscan.io'),
STRUCT('Moonriver'	,'MOON'	,'MOVR'	,'1285'	,'1285'	,'https://moonbeam.network/networks/moonriver/'	,'https://moonriver.moonscan.io'),
STRUCT('Moonrock old'	,'MOON'	,'ROC'	,'1286'	,'1286'	,''	,''),
STRUCT('Moonbase Alpha'	,'MOON'	,'DEV'	,'1287'	,'1287'	,'https://docs.moonbeam.network/networks/testnet/'	,'https://moonbase.moonscan.io'),
STRUCT('Moonrock'	,'MOON'	,'ROC'	,'1288'	,'1288'	,'https://docs.moonbeam.network/learn/platform/networks/overview/'	,''),
STRUCT('Boba Network Bobabeam'	,'Bobabeam'	,'BOBA'	,'1294'	,'1294'	,'https://boba.network'	,'https://blockexplorer.bobabeam.boba.network'),
STRUCT('Boba Network Bobabase Testnet'	,'Bobabase Testnet'	,'BOBA'	,'1297'	,'1297'	,'https://boba.network'	,'https://blockexplorer.bobabase.boba.network'),
STRUCT('Dos Fuji Subnet'	,'DOS'	,'DOS'	,'1311'	,'1311'	,'http://doschain.io/'	,'https://test.doscan.io'),
STRUCT('Alyx Mainnet'	,'ALYX'	,'ALYX'	,'1314'	,'1314'	,'https://www.alyxchain.com'	,'https://www.alyxscan.com'),
STRUCT('Aitd Mainnet'	,'AITD'	,'AITD'	,'1319'	,'1319'	,'https://www.aitd.io/'	,'https://aitd-explorer-new.aitd.io'),
STRUCT('Aitd Testnet'	,'AITD'	,'AITD'	,'1320'	,'1320'	,'https://www.aitd.io/'	,'https://block-explorer-testnet.aitd.io'),
STRUCT('Geth Testnet'	,'ETH'	,'ETH'	,'1337'	,'1337'	,'https://geth.ethereum.org'	,''),
STRUCT('Polygon zkEVM Testnet'	,'Polygon'	,'ETH'	,'1402'	,'1402'	,'https://polygon.technology/solutions/polygon-zkevm/'	,'https://explorer.public.zkevm-test.net'),
STRUCT('Sherpax Mainnet'	,'Sherpax Mainnet'	,'KSX'	,'1506'	,'1506'	,'https://sherpax.io/'	,'https://evm.sherpax.io'),
STRUCT('Sherpax Testnet'	,'Sherpax Testnet'	,'KSX'	,'1507'	,'1507'	,'https://sherpax.io/'	,'https://evm-pre.sherpax.io'),
STRUCT('Beagle Messaging Chain'	,'BMC'	,'BG'	,'1515'	,'1515'	,'https://beagle.chat/'	,'https://eth.beagle.chat'),
STRUCT('Catecoin Chain Mainnet'	,'Catechain'	,'CATE'	,'1618'	,'1618'	,'https://catechain.com'	,''),
STRUCT('Atheios'	,'ATH'	,'ATH'	,'1620'	,'11235813'	,'https://atheios.com'	,''),
STRUCT('Btachain'	,'btachain'	,'BTA'	,'1657'	,'1657'	,'https://bitcoinasset.io/'	,''),
STRUCT('LUDAN Mainnet'	,'LUDAN'	,'LUDAN'	,'1688'	,'1688'	,'https://www.ludan.org/'	,''),
STRUCT('Anytype EVM Chain'	,'ETH'	,'ANY'	,'1701'	,'1701'	,'https://evm.anytype.io'	,'https://explorer.anytype.io'),
STRUCT('TBSI Mainnet'	,'TBSI'	,'JINDA'	,'1707'	,'1707'	,'https://blockchain.or.th'	,''),
STRUCT('TBSI Testnet'	,'TBSI'	,'JINDA'	,'1708'	,'1708'	,'https://blockchain.or.th'	,''),
STRUCT('Rabbit Analog Testnet Chain'	,'rAna'	,'rAna'	,'1807'	,'1807'	,'https://rabbit.analogscan.com'	,'https://rabbit.analogscan.com'),
STRUCT('Cube Chain Mainnet'	,'Cube'	,'CUBE'	,'1818'	,'1818'	,'https://www.cube.network'	,'https://cubescan.network'),
STRUCT('Cube Chain Testnet'	,'Cube'	,'CUBET'	,'1819'	,'1819'	,'https://www.cube.network'	,'https://testnet.cubescan.network'),
STRUCT('Teslafunds'	,'TSF'	,'TSF'	,'1856'	,'1'	,'https://teslafunds.io'	,''),
STRUCT('BON Network'	,'BON'	,'BOY'	,'1898'	,'1'	,'https://boyanet.org'	,'https://explorer.boyanet.org:4001'),
STRUCT('ONUS Chain Testnet'	,'onus'	,'ONUS'	,'1945'	,'1945'	,'https://onuschain.io'	,'https://explorer-testnet.onuschain.io'),
STRUCT('ONUS Chain Mainnet'	,'onus'	,'ONUS'	,'1975'	,'1975'	,'https://onuschain.io'	,'https://explorer.onuschain.io'),
STRUCT('Eurus Testnet'	,'EUN'	,'EUN'	,'1984'	,'1984'	,'https://eurus.network'	,'https://testnetexplorer.eurus.network'),
STRUCT('EtherGem'	,'EGEM'	,'EGEM'	,'1987'	,'1987'	,'https://egem.io'	,''),
STRUCT('Dogechain Mainnet'	,'DC'	,'DOGE'	,'2000'	,'2000'	,'https://dogechain.dog'	,'https://explorer.dogechain.dog'),
STRUCT('Milkomeda C1 Mainnet'	,'milkAda'	,'mADA'	,'2001'	,'2001'	,'https://milkomeda.com'	,'https://explorer-mainnet-cardano-evm.c1.milkomeda.com'),
STRUCT('Milkomeda A1 Mainnet'	,'milkALGO'	,'mALGO'	,'2002'	,'2002'	,'https://milkomeda.com'	,'https://explorer-mainnet-algorand-rollup.a1.milkomeda.com'),
STRUCT('CloudWalk Testnet'	,'CloudWalk Testnet'	,'CWN'	,'2008'	,'2008'	,'https://cloudwalk.io'	,'https://explorer.testnet.cloudwalk.io'),
STRUCT('CloudWalk Mainnet'	,'CloudWalk Mainnet'	,'CWN'	,'2009'	,'2009'	,'https://cloudwalk.io'	,'https://explorer.mainnet.cloudwalk.io'),
STRUCT('PublicMint Devnet'	,'PublicMint'	,'USD'	,'2018'	,'2018'	,'https://publicmint.com'	,'https://explorer.dev.publicmint.io'),
STRUCT('PublicMint Testnet'	,'PublicMint'	,'USD'	,'2019'	,'2019'	,'https://publicmint.com'	,'https://explorer.tst.publicmint.io'),
STRUCT('PublicMint Mainnet'	,'PublicMint'	,'USD'	,'2020'	,'2020'	,'https://publicmint.com'	,'https://explorer.publicmint.io'),
STRUCT('Edgeware Mainnet'	,'EDG'	,'EDG'	,'2021'	,'2021'	,'http://edgewa.re'	,''),
STRUCT('Beresheet Testnet'	,'EDG'	,'tEDG'	,'2022'	,'2022'	,'http://edgewa.re'	,''),
STRUCT('Taycan Testnet'	,'Taycan'	,'tSFL'	,'2023'	,'2023'	,'https://hupayx.io'	,'https://evmscan-test.hupayx.io'),
STRUCT('Rangers Protocol Mainnet'	,'Rangers'	,'RPG'	,'2025'	,'2025'	,'https://rangersprotocol.com'	,'https://scan.rangersprotocol.com'),
STRUCT('Quokkacoin Mainnet'	,'Qkacoin'	,'QKA'	,'2077'	,'2077'	,'https://qkacoin.org'	,'https://explorer.qkacoin.org'),
STRUCT('Ecoball Mainnet'	,'ECO'	,'ECO'	,'2100'	,'2100'	,'https://ecoball.org'	,'https://scan.ecoball.org'),
STRUCT('Ecoball Testnet Espuma'	,'ECO'	,'ECO'	,'2101'	,'2101'	,'https://ecoball.org'	,'https://espuma-scan.ecoball.org'),
STRUCT('Exosama Network'	,'EXN'	,'SAMA'	,'2109'	,'2109'	,'https://moonsama.com'	,'https://explorer.exosama.com'),
STRUCT('BOSagora Mainnet'	,'ETH'	,'BOA'	,'2151'	,'2151'	,'https://docs.bosagora.org'	,'https://boascan.io'),
STRUCT('Findora Mainnet'	,'Findora'	,'FRA'	,'2152'	,'2152'	,'https://findora.org/'	,'https://evm.findorascan.io'),
STRUCT('Findora Testnet'	,'Testnet-anvil'	,'FRA'	,'2153'	,'2153'	,'https://findora.org/'	,'https://testnet-anvil.evm.findorascan.io'),
STRUCT('Findora Forge'	,'Testnet-forge'	,'FRA'	,'2154'	,'2154'	,'https://findora.org/'	,'https://testnet-forge.evm.findorascan.io'),
STRUCT('Bitcoin EVM'	,'Bitcoin EVM'	,'eBTC'	,'2203'	,'2203'	,'https://bitcoinevm.com'	,'https://explorer.bitcoinevm.com'),
STRUCT('Evanesco Mainnet'	,'EVA'	,'EVA'	,'2213'	,'2213'	,'https://evanesco.org/'	,'https://explorer.evanesco.org'),
STRUCT('Kava EVM Testnet'	,'KAVA'	,'TKAVA'	,'2221'	,'2221'	,'https://www.kava.io'	,'https://explorer.testnet.kava.io'),
STRUCT('Kava EVM'	,'KAVA'	,'KAVA'	,'2222'	,'2222'	,'https://www.kava.io'	,'https://explorer.kava.io'),
STRUCT('VChain Mainnet'	,'VChain'	,'VNDT'	,'2223'	,'2223'	,'https://bo.vcex.xyz/'	,'https://scan.vcex.xyz'),
STRUCT('Altcoinchain'	,'mainnet'	,'ALT'	,'2330'	,'12345'	,'https://altcoinchain.org'	,'https://expedition.altcoinchain.org'),
STRUCT('Kortho Mainnet'	,'Kortho Chain'	,'KTO'	,'2559'	,'2559'	,'https://www.kortho.io/'	,''),
STRUCT('TechPay Mainnet'	,'TPC'	,'TPC'	,'2569'	,'2569'	,'https://techpay.io/'	,'https://tpcscan.com'),
STRUCT('Redlight Chain Mainnet'	,'REDLC'	,'REDLC'	,'2611'	,'2611'	,'https://redlight.finance/'	,'https://redlightscan.finance'),
STRUCT('EZChain C-Chain Mainnet'	,'EZC'	,'EZC'	,'2612'	,'2612'	,'https://ezchain.com'	,'https://cchain-explorer.ezchain.com'),
STRUCT('EZChain C-Chain Testnet'	,'EZC'	,'EZC'	,'2613'	,'2613'	,'https://ezchain.com'	,'https://testnet-cchain-explorer.ezchain.com'),
STRUCT('BitYuan Mainnet'	,'BTY'	,'BTY'	,'2999'	,'2999'	,'https://www.bityuan.com'	,'https://mainnet.bityuan.com'),
STRUCT('CENNZnet Rata'	,'CENNZnet'	,'CPAY'	,'3000'	,'3000'	,'https://cennz.net'	,''),
STRUCT('CENNZnet Nikau'	,'CENNZnet'	,'CPAY'	,'3001'	,'3001'	,'https://cennz.net'	,'https://www.uncoverexplorer.com/?network=Nikau'),
STRUCT('Orlando Chain'	,'ORL'	,'ORL'	,'3031'	,'3031'	,'https://orlchain.com'	,'https://orlscan.com'),
STRUCT('Filecoin - Buildernet'	,'FIL'	,'FIL'	,'3141'	,'3141'	,'https://filecoin.io'	,''),
STRUCT('Debounce Subnet Testnet'	,'Debounce Network'	,'DB'	,'3306'	,'3306'	,'https://debounce.network'	,'https://explorer.debounce.network'),
STRUCT('ZCore Testnet'	,'Beach'	,'ZCR'	,'3331'	,'3331'	,'https://zcore.cash'	,''),
STRUCT('Web3Q Testnet'	,'Web3Q'	,'W3Q'	,'3333'	,'3333'	,'https://testnet.web3q.io/home.w3q/'	,'https://explorer.testnet.web3q.io'),
STRUCT('Web3Q Galileo'	,'Web3Q'	,'W3Q'	,'3334'	,'3334'	,'https://galileo.web3q.io/home.w3q/'	,'https://explorer.galileo.web3q.io'),
STRUCT('Paribu Net Mainnet'	,'PRB'	,'PRB'	,'3400'	,'3400'	,'https://net.paribu.com'	,'https://explorer.paribu.network'),
STRUCT('Paribu Net Testnet'	,'PRB'	,'PRB'	,'3500'	,'3500'	,'https://net.paribu.com'	,'https://testnet.paribuscan.com'),
STRUCT('JFIN Chain'	,'JFIN'	,'jfin'	,'3501'	,'3501'	,'https://jfinchain.com'	,'https://exp.jfinchain.com'),
STRUCT('Pandonet'	,'Pando'	,'PTX'	,'3601'	,'3601'	,'https://www.pandoproject.org/'	,'https://explorer.pandoproject.org'),
STRUCT('Pando Testnet'	,'Pando'	,'PTX'	,'3602'	,'3602'	,'https://www.pandoproject.org/'	,'https://testnet.explorer.pandoproject.org'),
STRUCT('Metacodechain'	,'metacode'	,'J'	,'3666'	,'3666'	,'https://j.blockcoach.com:8089'	,'https://j.blockcoach.com:8089'),
STRUCT('Bittex Mainnet'	,'BTX'	,'BTX'	,'3690'	,'3690'	,'https://bittexscan.com'	,'https://bittexscan.com'),
STRUCT('Crossbell'	,'Crossbell'	,'CSB'	,'3737'	,'3737'	,'https://crossbell.io'	,'https://scan.crossbell.io'),
STRUCT('DYNO Mainnet'	,'DYNO'	,'DYNO'	,'3966'	,'3966'	,'https://dynoprotocol.com'	,'https://dynoscan.io'),
STRUCT('DYNO Testnet'	,'DYNO'	,'tDYNO'	,'3967'	,'3967'	,'https://dynoprotocol.com'	,'https://testnet.dynoscan.io'),
STRUCT('YuanChain Mainnet'	,'YCC'	,'YCC'	,'3999'	,'3999'	,'https://www.yuan.org'	,'https://mainnet.yuan.org'),
STRUCT('Fantom Testnet'	,'FTM'	,'FTM'	,'4002'	,'4002'	,'https://docs.fantom.foundation/quick-start/short-guide#fantom-testnet'	,'https://testnet.ftmscan.com'),
STRUCT('Boba Network Bobaopera Testnet'	,'Bobaopera Testnet'	,'BOBA'	,'4051'	,'4051'	,'https://boba.network'	,'https://blockexplorer.testnet.bobaopera.boba.network'),
STRUCT('AIOZ Network Testnet'	,'AIOZ'	,'AIOZ'	,'4102'	,'4102'	,'https://aioz.network'	,'https://testnet.explorer.aioz.network'),
STRUCT('PHI Network V1'	,'PHI V1'	,'Φ'	,'4181'	,'4181'	,'https://phi.network'	,'https://explorer.phi.network'),
STRUCT('Boba Network Bobafuji Testnet'	,'Bobafuji Testnet'	,'BOBA'	,'4328'	,'4328'	,'https://boba.network'	,'https://blockexplorer.testnet.avax.boba.network'),
STRUCT('IoTeX Network Mainnet'	,'iotex.io'	,'IOTX'	,'4689'	,'4689'	,'https://iotex.io'	,'https://iotexscan.io'),
STRUCT('IoTeX Network Testnet'	,'iotex.io'	,'IOTX'	,'4690'	,'4690'	,'https://iotex.io'	,'https://testnet.iotexscan.io'),
STRUCT('Venidium Testnet'	,'XVM'	,'XVM'	,'4918'	,'4918'	,'https://venidium.io'	,'https://evm-testnet.venidiumexplorer.com'),
STRUCT('Venidium Mainnet'	,'XVM'	,'XVM'	,'4919'	,'4919'	,'https://venidium.io'	,'https://evm.venidiumexplorer.com'),
STRUCT('TLChain Network Mainnet'	,'TLC'	,'TLC'	,'5177'	,'5177'	,'https://tlchain.network/'	,'https://explorer.tlchain.network'),
STRUCT('EraSwap Mainnet'	,'ESN'	,'ES'	,'5197'	,'5197'	,'https://eraswap.info/'	,''),
STRUCT('Humanode Mainnet'	,'HMND'	,'HMND'	,'5234'	,'5234'	,'https://humanode.io'	,''),
STRUCT('Firechain Mainnet'	,'FIRE'	,'FIRE'	,'5290'	,'5290'	,'https://thefirechain.com'	,''),
STRUCT('Uzmi Network Mainnet'	,'UZMI'	,'UZMI'	,'5315'	,'5315'	,'https://uzmigames.com.br/'	,''),
STRUCT('Nahmii Mainnet'	,'Nahmii'	,'ETH'	,'5551'	,'5551'	,'https://nahmii.io'	,'https://explorer.nahmii.io'),
STRUCT('Nahmii Testnet'	,'Nahmii'	,'ETH'	,'5553'	,'5553'	,'https://nahmii.io'	,'https://explorer.testnet.nahmii.io'),
STRUCT('Syscoin Tanenbaum Testnet'	,'SYS'	,'tSYS'	,'5700'	,'5700'	,'https://syscoin.org'	,'https://tanenbaum.io'),
STRUCT('Digest Swarm Chain'	,'DSC'	,'DGCC'	,'5777'	,'5777'	,'https://digestgroup.ltd'	,'https://explorer.digestgroup.ltd'),
STRUCT('Ontology Testnet'	,'Ontology'	,'ONG'	,'5851'	,'5851'	,'https://ont.io/'	,'https://explorer.ont.io/testnet'),
STRUCT('Wegochain Rubidium Mainnet'	,'RBD'	,'RBD'	,'5869'	,'5869'	,'https://www.wegochain.io'	,'https://scan2.wegochain.io'),
STRUCT('Tres Leches Testnet'	,'TresLeches'	,'TRES'	,'6065'	,'6065'	,'https://tresleches.finance'	,'https://explorer-test.tresleches.finance'),
STRUCT('Tres Leches Mainnet'	,'TresLeches'	,'TRES'	,'6066'	,'6066'	,'https://tresleches.finance'	,'https://explorer.tresleches.finance'),
STRUCT('Pixie Chain Mainnet'	,'PixieChain'	,'PIX'	,'6626'	,'6626'	,'https://chain.pixie.xyz'	,'https://scan.chain.pixie.xyz'),
STRUCT('Tomb Chain Mainnet'	,'Tomb Chain'	,'TOMB'	,'6969'	,'6969'	,'https://tombchain.com/'	,'https://tombscout.com'),
STRUCT('PolySmartChain'	,'PSC'	,'PSC'	,'6999'	,'6999'	,'https://www.polysmartchain.com/'	,''),
STRUCT('ZetaChain Mainnet'	,'ZetaChain'	,'ZETA'	,'7000'	,'7000'	,'https://docs.zetachain.com/'	,'https://explorer.mainnet.zetachain.com'),
STRUCT('ZetaChain Athens Testnet'	,'ZetaChain'	,'aZETA'	,'7001'	,'7001'	,'https://docs.zetachain.com/'	,'https://explorer.athens.zetachain.com'),
STRUCT('Ella the heart'	,'ella'	,'ELLA'	,'7027'	,'7027'	,'https://ella.network'	,'https://ella.network'),
STRUCT('Planq Mainnet'	,'Planq'	,'PLQ'	,'7070'	,'7070'	,'https://planq.network'	,'https://evm.planq.network'),
STRUCT('Shyft Mainnet'	,'SHYFT'	,'SHYFT'	,'7341'	,'7341'	,'https://shyft.network'	,'https://bx.shyft.network'),
STRUCT('Canto'	,'Canto'	,'CANTO'	,'7700'	,'7700'	,'https://canto.io'	,'https://evm.explorer.canto.io'),
STRUCT('Rise of the Warbots Testnet'	,'nmactest'	,'NMAC'	,'7777'	,'7777'	,'https://riseofthewarbots.com/'	,'https://testnet.avascan.info/blockchain/2mZ9doojfwHzXN3VXDQELKnKyZYxv7833U8Yq5eTfFx3hxJtiy'),
STRUCT('Hazlor Testnet'	,'SCAS'	,'TSCAS'	,'7878'	,'7878'	,'https://hazlor.com'	,'https://explorer.hazlor.com'),
STRUCT('Teleport'	,'Teleport'	,'TELE'	,'8000'	,'8000'	,'https://teleport.network'	,'https://evm-explorer.teleport.network'),
STRUCT('Teleport Testnet'	,'Teleport'	,'TELE'	,'8001'	,'8001'	,'https://teleport.network'	,'https://evm-explorer.testnet.teleport.network'),
STRUCT('MDGL Testnet'	,'MDGL'	,'MDGLT'	,'8029'	,'8029'	,'https://mdgl.io'	,''),
STRUCT('Shardeum Liberty 1.6'	,'Shardeum'	,'SHM'	,'8080'	,'8080'	,'https://docs.shardeum.org/'	,'https://explorer-liberty10.shardeum.org'),
STRUCT('Shardeum Liberty 2.0'	,'Shardeum'	,'SHM'	,'8081'	,'8081'	,'https://docs.shardeum.org/'	,'https://explorer-liberty20.shardeum.org'),
STRUCT('Qitmeer Network Testnet'	,'MEER'	,'MEER-T'	,'8131'	,'8131'	,'https://github.com/Qitmeer'	,'https://testnet.qng.meerscan.io'),
STRUCT('Klaytn Mainnet Cypress'	,'KLAY'	,'KLAY'	,'8217'	,'8217'	,'https://www.klaytn.com/'	,'https://scope.klaytn.com'),
STRUCT('KorthoTest'	,'Kortho'	,'KTO'	,'8285'	,'8285'	,'https://www.kortho.io/'	,''),
STRUCT('Toki Network'	,'TOKI'	,'TOKI'	,'8654'	,'8654'	,'https://www.buildwithtoki.com'	,''),
STRUCT('Toki Testnet'	,'TOKI'	,'TOKI'	,'8655'	,'8655'	,'https://www.buildwithtoki.com'	,''),
STRUCT('TOOL Global Mainnet'	,'OLO'	,'OLO'	,'8723'	,'8723'	,'https://ibdt.io'	,'https://www.olo.network'),
STRUCT('TOOL Global Testnet'	,'OLO'	,'OLO'	,'8724'	,'8724'	,'https://testnet-explorer.wolot.io'	,''),
STRUCT('Alph Network'	,'ALPH'	,'ALPH'	,'8738'	,'8738'	,'https://alph.network'	,'https://explorer.alph.network'),
STRUCT('Ambros Chain Testnet'	,'ambroschain'	,'AMBROS'	,'8888'	,'8888'	,'https://test.ambros.network'	,'https://testnet.ambrosscan.com'),
STRUCT('Vyvo Smart Chain'	,'VSC'	,'VSC'	,'8889'	,'8889'	,'https://vsc-dataseed.vyvo.org'	,''),
STRUCT('Mammoth Mainnet'	,'MMT'	,'MMT'	,'8898'	,'8898'	,'https://mmtchain.io/'	,'https://mmtscan.io'),
STRUCT('bloxberg'	,'bloxberg'	,'U+25B3'	,'8995'	,'8995'	,'https://bloxberg.org'	,''),
STRUCT('Evmos Testnet'	,'Evmos'	,'tEVMOS'	,'9000'	,'9000'	,'https://evmos.org'	,'https://evm.evmos.dev'),
STRUCT('Evmos'	,'Evmos'	,'EVMOS'	,'9001'	,'9001'	,'https://evmos.org'	,'https://evm.evmos.org'),
STRUCT('BerylBit Mainnet'	,'BRB'	,'BRB'	,'9012'	,'9012'	,'https://www.beryl-bit.com'	,'https://explorer.berylbit.io'),
STRUCT('Genesis Coin'	,'Genesis'	,'GNC'	,'9100'	,'9100'	,'https://genesis-gn.com'	,''),
STRUCT('Rinia Testnet'	,'FIRE'	,'FIRE'	,'9170'	,'9170'	,'https://thefirechain.com'	,''),
STRUCT('Rangers Protocol Testnet Robin'	,'Rangers'	,'tRPG'	,'9527'	,'9527'	,'https://rangersprotocol.com'	,'https://robin-rangersscan.rangersprotocol.com'),
STRUCT('QEasyWeb3 Testnet'	,'QET'	,'QET'	,'9528'	,'9528'	,'https://www.qeasyweb3.com'	,'https://www.qeasyweb3.com'),
STRUCT('Boba Network BNB Testnet'	,'Boba BNB Testnet'	,'BOBA'	,'9728'	,'9728'	,'https://boba.network'	,'https://blockexplorer.testnet.bnb.boba.network'),
STRUCT('myOwn Testnet'	,'myOwn'	,'MYN'	,'9999'	,'9999'	,'https://docs.bccloud.net/'	,''),
STRUCT('Smart Bitcoin Cash'	,'smartBCH'	,'BCH'	,'10000'	,'10000'	,'https://smartbch.org/'	,''),
STRUCT('Smart Bitcoin Cash Testnet'	,'smartBCHTest'	,'BCHT'	,'10001'	,'10001'	,'http://smartbch.org/'	,''),
STRUCT('Gon Chain'	,'GonChain'	,'GT'	,'10024'	,'10024'	,''	,'https://gonscan.com'),
STRUCT('SJATSH'	,'ETH'	,'ETH'	,'10086'	,'10086'	,'https://sjis.me'	,''),
STRUCT('Blockchain Genesis Mainnet'	,'GEN'	,'GEN'	,'10101'	,'10101'	,'https://www.xixoio.com/'	,''),
STRUCT('Chiado Testnet'	,'CHI'	,'xDAI'	,'10200'	,'10200'	,'https://docs.gnosischain.com'	,'https://blockscout.chiadochain.net'),
STRUCT('0XTade'	,'0XTade Chain'	,'0XT'	,'10248'	,'10248'	,'https://www.0xtrade.finance/'	,'https://www.0xtscan.com'),
STRUCT('Numbers Mainnet'	,'NUM'	,'NUM'	,'10507'	,'10507'	,'https://numbersprotocol.io'	,'https://mainnet.num.network'),
STRUCT('Numbers Testnet'	,'NUM'	,'NUM'	,'10508'	,'10508'	,'https://numbersprotocol.io'	,'https://testnet.num.network'),
STRUCT('CryptoCoinPay'	,'CCP'	,'CCP'	,'10823'	,'10823'	,'https://www.cryptocoinpay.co'	,'https://cryptocoinpay.info'),
STRUCT('Quadrans Blockchain'	,'QDC'	,'QDC'	,'10946'	,'10946'	,'https://quadrans.io'	,'https://explorer.quadrans.io'),
STRUCT('Quadrans Blockchain Testnet'	,'tQDC'	,'tQDC'	,'10947'	,'10947'	,'https://quadrans.io'	,'https://explorer.testnet.quadrans.io'),
STRUCT('Astra'	,'Astra'	,'ASA'	,'11110'	,'11110'	,'https://astranaut.io'	,'https://explorer.astranaut.io'),
STRUCT('WAGMI'	,'WAGMI'	,'WGM'	,'11111'	,'11111'	,'https://subnets-test.avax.network/wagmi/details'	,'https://subnets-test.avax.network/wagmi'),
STRUCT('Astra Testnet'	,'Astra'	,'tASA'	,'11115'	,'11115'	,'https://astranaut.io'	,'https://explorer.astranaut.dev'),
STRUCT('Shyft Testnet'	,'SHYFTT'	,'SHYFTT'	,'11437'	,'11437'	,'https://shyft.network'	,'https://bx.testnet.shyft.network'),
STRUCT('SanR Chain'	,'SanRChain'	,'nSAN'	,'11888'	,'11888'	,'https://sanr.app'	,'https://sanrchain-explorer.santiment.net'),
STRUCT('Singularity ZERO Testnet'	,'ZERO'	,'tZERO'	,'12051'	,'12051'	,'https://www.singularity.gold'	,'https://betaenv.singularity.gold:18002'),
STRUCT('Singularity ZERO Mainnet'	,'ZERO'	,'ZERO'	,'12052'	,'12052'	,'https://www.singularity.gold'	,'https://zeroscan.singularity.gold'),
STRUCT('Step Testnet'	,'STEP'	,'FITFI'	,'12345'	,'12345'	,'https://step.network'	,'https://testnet.stepscan.io'),
STRUCT('SPS'	,'SPS'	,'ECG'	,'13000'	,'13000'	,'https://ssquad.games/'	,'http://spsscan.ssquad.games'),
STRUCT('Phoenix Mainnet'	,'Phoenix'	,'PHX'	,'13381'	,'13381'	,'https://cryptophoenix.org/phoenix'	,'https://phoenixplorer.com'),
STRUCT('SPS Testnet'	,'SPS-Testnet'	,'ECG'	,'14000'	,'14000'	,'https://ssquad.games/'	,'https://explorer.3sps.net'),
STRUCT('Trust EVM Testnet'	,'Trust EVM Testnet'	,'EVM'	,'15555'	,'15555'	,'https://www.trust.one/'	,'https://trustscan.one'),
STRUCT('MetaDot Mainnet'	,'MTT'	,'MTT'	,'16000'	,'16000'	,'https://metadot.network'	,''),
STRUCT('MetaDot Testnet'	,'MTTTest'	,'MTTest'	,'16001'	,'16001'	,'https://metadot.network'	,''),
STRUCT('IVAR Chain Testnet'	,'IVAR'	,'tIVAR'	,'16888'	,'16888'	,'https://ivarex.com'	,'https://testnet.ivarscan.com'),
STRUCT('Frontier of Dreams Testnet'	,'Game Network'	,'ZKST'	,'18000'	,'18000'	,'https://goexosphere.com'	,'https://explorer.fod.games'),
STRUCT('Proof Of Memes'	,'POM'	,'POM'	,'18159'	,'18159'	,'https://proofofmemes.org'	,'https://memescan.io'),
STRUCT('BTCIX Network'	,'BTCIX'	,'BTCIX'	,'19845'	,'19845'	,'https://bitcolojix.org'	,'https://btcixscan.com'),
STRUCT('Callisto Testnet'	,'CLO'	,'CLO'	,'20729'	,'79'	,'https://callisto.network'	,''),
STRUCT('CENNZnet Azalea'	,'CENNZnet'	,'CPAY'	,'21337'	,'21337'	,'https://cennz.net'	,'https://uncoverexplorer.com'),
STRUCT('omChain Mainnet'	,'OML'	,'OMC'	,'21816'	,'21816'	,'https://omchain.io'	,'https://explorer.omchain.io'),
STRUCT('Taycan'	,'Taycan'	,'SFL'	,'22023'	,'22023'	,'https://hupayx.io'	,'https://taycan-evmscan.hupayx.io'),
STRUCT('MAP Mainnet'	,'MAP'	,'MAP'	,'22776'	,'22776'	,'https://maplabs.io'	,'https://mapscan.io'),
STRUCT('Opside Testnet'	,'Opside'	,'IDE'	,'23118'	,'23118'	,'https://opside.network'	,'https://opside.info'),
STRUCT('Webchain'	,'WEB'	,'WEB'	,'24484'	,'37129'	,'https://webchain.network'	,''),
STRUCT('MintMe.com Coin'	,'MINTME'	,'MINTME'	,'24734'	,'37480'	,'https://www.mintme.com'	,''),
STRUCT('OasisChain Mainnet'	,'OasisChain'	,'OAC'	,'26863'	,'26863'	,'https://scan.oasischain.io'	,'https://scan.oasischain.io'),
STRUCT('Optimism Bedrock (Goerli Alpha Testnet)'	,'ETH'	,'ETH'	,'28528'	,'28528'	,'https://community.optimism.io/docs/developers/bedrock'	,'https://blockscout.com/optimism/bedrock-alpha'),
STRUCT('Piece testnet'	,'PieceNetwork'	,'ECE'	,'30067'	,'30067'	,'https://piecenetwork.com'	,'https://testnet-scan.piecenetwork.com'),
STRUCT('Ethersocial Network'	,'ESN'	,'ESN'	,'31102'	,'1'	,'https://ethersocial.org'	,''),
STRUCT('GoChain Testnet'	,'GO'	,'GO'	,'31337'	,'31337'	,'https://gochain.io'	,'https://testnet-explorer.gochain.io'),
STRUCT('Filecoin - Wallaby testnet'	,'FIL'	,'tFIL'	,'31415'	,'31415'	,'https://filecoin.io'	,'https://explorer.glif.io/wallaby'),
STRUCT('Bitgert Mainnet'	,'Brise'	,'Brise'	,'32520'	,'32520'	,'https://bitgert.com/'	,'https://brisescan.com'),
STRUCT('Fusion Mainnet'	,'FSN'	,'FSN'	,'32659'	,'32659'	,'https://www.fusion.org/'	,''),
STRUCT('Aves Mainnet'	,'AVS'	,'AVS'	,'33333'	,'33333'	,'https://avescoin.io'	,'https://avescan.io'),
STRUCT('Q Mainnet'	,'Q'	,'Q'	,'35441'	,'35441'	,'https://q.org'	,'https://explorer.q.org'),
STRUCT('Q Testnet'	,'Q'	,'Q'	,'35443'	,'35443'	,'https://q.org/'	,'https://explorer.qtestnet.org'),
STRUCT('Energi Mainnet'	,'NRG'	,'NRG'	,'39797'	,'39797'	,'https://www.energi.world/'	,''),
STRUCT('Opulent-X BETA'	,'Opulent-X'	,'OXYN'	,'41500'	,'41500'	,'https://beta.opulent-x.com'	,'https://explorer.opulent-x.com'),
STRUCT('pegglecoin'	,'42069'	,'peggle'	,'42069'	,'42069'	,'https://teampeggle.com'	,''),
STRUCT('Arbitrum One'	,'ETH'	,'ETH'	,'42161'	,'42161'	,'https://arbitrum.io'	,'https://arbiscan.io'),
STRUCT('Arbitrum Nova'	,'ETH'	,'ETH'	,'42170'	,'42170'	,'https://arbitrum.io'	,'https://nova-explorer.arbitrum.io'),
STRUCT('Celo Mainnet'	,'CELO'	,'CELO'	,'42220'	,'42220'	,'https://docs.celo.org/'	,'https://celoscan.io'),
STRUCT('Oasis Emerald ParaTime Testnet'	,'Emerald'	,'ROSE'	,'42261'	,'42261'	,'https://docs.oasis.dev/general/developer-resources/overview'	,'https://testnet.explorer.emerald.oasis.dev'),
STRUCT('Oasis Emerald ParaTime Mainnet'	,'Emerald'	,'ROSE'	,'42262'	,'42262'	,'https://docs.oasis.dev/general/developer-resources/overview'	,'https://explorer.emerald.oasis.dev'),
STRUCT('Athereum'	,'ATH'	,'ATH'	,'43110'	,'43110'	,'https://athereum.ava.network'	,''),
STRUCT('Avalanche Fuji Testnet'	,'AVAX'	,'AVAX'	,'43113'	,'1'	,'https://cchain.explorer.avax-test.network'	,'https://testnet.snowtrace.io'),
STRUCT('Avalanche C-Chain'	,'AVAX'	,'AVAX'	,'43114'	,'43114'	,'https://www.avax.network/'	,'https://snowtrace.io'),
STRUCT('Boba Avax'	,'Boba Avax'	,'BOBA'	,'43288'	,'43288'	,'https://docs.boba.network/for-developers/network-avalanche'	,'https://blockexplorer.avax.boba.network'),
STRUCT('Celo Alfajores Testnet'	,'CELO'	,'CELO'	,'44787'	,'44787'	,'https://docs.celo.org/'	,'https://celoscan.io'),
STRUCT('Autobahn Network'	,'TXL'	,'TXL'	,'45000'	,'45000'	,'https://autobahn.network'	,'https://explorer.autobahn.network'),
STRUCT('REI Network'	,'REI'	,'REI'	,'47805'	,'47805'	,'https://rei.network/'	,'https://scan.rei.network'),
STRUCT('Bifrost Testnet1'	,'BFC'	,'BFC'	,'49088'	,'49088'	,'https://testnet.thebifrost.io'	,'https://explorer.testnet.thebifrost.io'),
STRUCT('Energi Testnet'	,'NRG'	,'NRG'	,'49797'	,'49797'	,'https://www.energi.world/'	,''),
STRUCT('GTON Testnet'	,'GTON Testnet'	,'GCD'	,'50021'	,'50021'	,'https://gton.capital'	,'https://explorer.testnet.gton.network'),
STRUCT('DFK Chain'	,'DFK'	,'JEWEL'	,'53935'	,'53935'	,'https://defikingdoms.com'	,'https://explorer.dfkchain.com'),
STRUCT('REI Chain Mainnet'	,'REI'	,'REI'	,'55555'	,'55555'	,'https://reichain.io'	,'https://reiscan.com'),
STRUCT('REI Chain Testnet'	,'REI'	,'tREI'	,'55556'	,'55556'	,'https://reichain.io'	,'https://testnet.reiscan.com'),
STRUCT('Thinkium Testnet Chain 0'	,'Thinkium'	,'TKM'	,'60000'	,'60000'	,'https://thinkium.net/'	,'https://test0.thinkiumscan.net'),
STRUCT('Thinkium Testnet Chain 1'	,'Thinkium'	,'TKM'	,'60001'	,'60001'	,'https://thinkium.net/'	,'https://test1.thinkiumscan.net'),
STRUCT('Thinkium Testnet Chain 2'	,'Thinkium'	,'TKM'	,'60002'	,'60002'	,'https://thinkium.net/'	,'https://test2.thinkiumscan.net'),
STRUCT('Thinkium Testnet Chain 103'	,'Thinkium'	,'TKM'	,'60103'	,'60103'	,'https://thinkium.net/'	,'https://test103.thinkiumscan.net'),
STRUCT('DoKEN Super Chain Mainnet'	,'DoKEN Super Chain'	,'DKN'	,'61916'	,'61916'	,'https://doken.dev/'	,'https://explore.doken.dev'),
STRUCT('Celo Baklava Testnet'	,'CELO'	,'CELO'	,'62320'	,'62320'	,'https://docs.celo.org/'	,''),
STRUCT('MultiVAC Mainnet'	,'MultiVAC'	,'MTV'	,'62621'	,'62621'	,'https://mtv.ac'	,'https://e.mtv.ac'),
STRUCT('eCredits Mainnet'	,'ECS'	,'ECS'	,'63000'	,'63000'	,'https://ecredits.com'	,'https://explorer.ecredits.com'),
STRUCT('eCredits Testnet'	,'ECS'	,'ECS'	,'63001'	,'63001'	,'https://ecredits.com'	,'https://explorer.tst.ecredits.com'),
STRUCT('SiriusNet'	,'SIN'	,'MCD'	,'67390'	,'67390'	,'https://macaucasinolisboa.xyz'	,'https://siriusnet.tryethernal.com'),
STRUCT('Condrieu'	,'ETH'	,'CTE'	,'69420'	,'69420'	,'https://condrieu.ethdevops.io'	,'https://explorer.condrieu.ethdevops.io'),
STRUCT('Thinkium Mainnet Chain 0'	,'Thinkium'	,'TKM'	,'70000'	,'70000'	,'https://thinkium.net/'	,'https://chain0.thinkiumscan.net'),
STRUCT('Thinkium Mainnet Chain 1'	,'Thinkium'	,'TKM'	,'70001'	,'70001'	,'https://thinkium.net/'	,'https://chain1.thinkiumscan.net'),
STRUCT('Thinkium Mainnet Chain 2'	,'Thinkium'	,'TKM'	,'70002'	,'70002'	,'https://thinkium.net/'	,'https://chain2.thinkiumscan.net'),
STRUCT('Thinkium Mainnet Chain 103'	,'Thinkium'	,'TKM'	,'70103'	,'70103'	,'https://thinkium.net/'	,'https://chain103.thinkiumscan.net'),
STRUCT('Polyjuice Testnet'	,'CKB'	,'CKB'	,'71393'	,'1'	,'https://github.com/nervosnetwork/godwoken'	,''),
STRUCT('Godwoken Testnet (V1.1)'	,'GWT'	,'pCKB'	,'71401'	,'71401'	,'https://www.nervos.org'	,'https://gw-testnet-explorer.nervosdao.community'),
STRUCT('Godwoken Mainnet'	,'GWT'	,'pCKB'	,'71402'	,'71402'	,'https://www.nervos.org'	,'https://gw-mainnet-explorer.nervosdao.community'),
STRUCT('Energy Web Volta Testnet'	,'Volta'	,'VT'	,'73799'	,'73799'	,'https://energyweb.org'	,''),
STRUCT('Mixin Virtual Machine'	,'MVM'	,'ETH'	,'73927'	,'73927'	,'https://mvm.dev'	,'https://scan.mvm.dev'),
STRUCT('ResinCoin Mainnet'	,'RESIN'	,'RESIN'	,'75000'	,'75000'	,'https://resincoin.dev'	,'https://explorer.resincoin.dev'),
STRUCT('Firenze test network'	,'ETH'	,'FIN'	,'78110'	,'78110'	,'https://primusmoney.com'	,''),
STRUCT('Mumbai'	,'Polygon'	,'MATIC'	,'80001'	,'80001'	,'https://polygon.technology/'	,'https://mumbai.polygonscan.com'),
STRUCT('IVAR Chain Mainnet'	,'IVAR'	,'IVAR'	,'88888'	,'88888'	,'https://ivarex.com'	,'https://ivarscan.com'),
STRUCT('Beverly Hills'	,'ETH'	,'BVE'	,'90210'	,'90210'	,'https://beverlyhills.ethdevops.io'	,'https://explorer.beverlyhills.ethdevops.io'),
STRUCT('Lambda Testnet'	,'Lambda'	,'LAMB'	,'92001'	,'92001'	,'https://lambda.im'	,'https://explorer.lambda.top'),
STRUCT('UB Smart Chain(testnet)'	,'USC'	,'UBC'	,'99998'	,'99998'	,'https://www.ubchain.site'	,''),
STRUCT('UB Smart Chain'	,'USC'	,'UBC'	,'99999'	,'99999'	,'https://www.ubchain.site/'	,''),
STRUCT('QuarkChain Mainnet Root'	,'QuarkChain'	,'QKC'	,'100000'	,'100000'	,'https://www.quarkchain.io'	,''),
STRUCT('QuarkChain Mainnet Shard 0'	,'QuarkChain'	,'QKC'	,'100001'	,'100001'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/0'),
STRUCT('QuarkChain Mainnet Shard 1'	,'QuarkChain'	,'QKC'	,'100002'	,'100002'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/1'),
STRUCT('QuarkChain Mainnet Shard 2'	,'QuarkChain'	,'QKC'	,'100003'	,'100003'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/2'),
STRUCT('QuarkChain Mainnet Shard 3'	,'QuarkChain'	,'QKC'	,'100004'	,'100004'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/3'),
STRUCT('QuarkChain Mainnet Shard 4'	,'QuarkChain'	,'QKC'	,'100005'	,'100005'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/4'),
STRUCT('QuarkChain Mainnet Shard 5'	,'QuarkChain'	,'QKC'	,'100006'	,'100006'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/5'),
STRUCT('QuarkChain Mainnet Shard 6'	,'QuarkChain'	,'QKC'	,'100007'	,'100007'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/6'),
STRUCT('QuarkChain Mainnet Shard 7'	,'QuarkChain'	,'QKC'	,'100008'	,'100008'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/7'),
STRUCT('Deprecated Chiado Testnet'	,'CHI1'	,'xDAI'	,'100100'	,'100100'	,'https://docs.gnosischain.com'	,'https://blockscout-chiado.gnosistestnet.com'),
STRUCT('Crystaleum'	,'crystal'	,'◈'	,'103090'	,'1'	,'https://crystaleum.org'	,'https://scan.crystaleum.org'),
STRUCT('BROChain Mainnet'	,'BRO'	,'BRO'	,'108801'	,'108801'	,'https://brochain.org'	,'https://explorer.brochain.org'),
STRUCT('QuarkChain Devnet Root'	,'QuarkChain'	,'QKC'	,'110000'	,'110000'	,'https://www.quarkchain.io'	,''),
STRUCT('QuarkChain Devnet Shard 0'	,'QuarkChain'	,'QKC'	,'110001'	,'110001'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/0'),
STRUCT('QuarkChain Devnet Shard 1'	,'QuarkChain'	,'QKC'	,'110002'	,'110002'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/1'),
STRUCT('QuarkChain Devnet Shard 2'	,'QuarkChain'	,'QKC'	,'110003'	,'110003'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/2'),
STRUCT('QuarkChain Devnet Shard 3'	,'QuarkChain'	,'QKC'	,'110004'	,'110004'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/3'),
STRUCT('QuarkChain Devnet Shard 4'	,'QuarkChain'	,'QKC'	,'110005'	,'110005'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/4'),
STRUCT('QuarkChain Devnet Shard 5'	,'QuarkChain'	,'QKC'	,'110006'	,'110006'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/5'),
STRUCT('QuarkChain Devnet Shard 6'	,'QuarkChain'	,'QKC'	,'110007'	,'110007'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/6'),
STRUCT('QuarkChain Devnet Shard 7'	,'QuarkChain'	,'QKC'	,'110008'	,'110008'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/7'),
STRUCT('ETND Chain Mainnets'	,'ETND'	,'ETND'	,'131419'	,'131419'	,'https://www.etnd.pro'	,'https://scan.etnd.pro'),
STRUCT('Condor Test Network'	,'CONDOR'	,'CONDOR'	,'188881'	,'188881'	,'https://condor.systems'	,'https://explorer.condor.systems'),
STRUCT('Milkomeda C1 Testnet'	,'milkTAda'	,'mTAda'	,'200101'	,'200101'	,'https://milkomeda.com'	,'https://explorer-devnet-cardano-evm.c1.milkomeda.com'),
STRUCT('Milkomeda A1 Testnet'	,'milkTAlgo'	,'mTAlgo'	,'200202'	,'200202'	,'https://milkomeda.com'	,'https://explorer-devnet-algorand-rollup.a1.milkomeda.com'),
STRUCT('Akroma'	,'AKA'	,'AKA'	,'200625'	,'200625'	,'https://akroma.io'	,''),
STRUCT('Alaya Mainnet'	,'Alaya'	,'atp'	,'201018'	,'1'	,'https://www.alaya.network/'	,'https://scan.alaya.network'),
STRUCT('Alaya Dev Testnet'	,'Alaya'	,'atp'	,'201030'	,'1'	,'https://www.alaya.network/'	,'https://devnetscan.alaya.network'),
STRUCT('Jellie'	,'ETH'	,'TWL'	,'202624'	,'202624'	,'https://twala.io/'	,'https://jellie.twala.io'),
STRUCT('PlatON Mainnet'	,'PlatON'	,'lat'	,'210425'	,'1'	,'https://www.platon.network'	,'https://scan.platon.network'),
STRUCT('Haymo Testnet'	,'tHYM'	,'HYM'	,'234666'	,'234666'	,'https://haymoswap.web.app/'	,''),
STRUCT('ARTIS sigma1'	,'ARTIS'	,'ATS'	,'246529'	,'246529'	,'https://artis.eco'	,''),
STRUCT('ARTIS Testnet tau1'	,'ARTIS'	,'tATS'	,'246785'	,'246785'	,'https://artis.network'	,''),
STRUCT('CMP-Mainnet'	,'CMP'	,'CMP'	,'256256'	,'256256'	,'https://caduceus.foundation/'	,'https://mainnet.scan.caduceus.foundation'),
STRUCT('Gear Zero Network Testnet'	,'GearZero'	,'GZN'	,'266256'	,'266256'	,'https://token.gearzero.ca/testnet'	,''),
STRUCT('Social Smart Chain Mainnet'	,'SoChain'	,'$OC'	,'281121'	,'281121'	,'https://digitalnext.business/SocialSmartChain'	,''),
STRUCT('Filecoin - Calibration testnet'	,'FIL'	,'tFIL'	,'314159'	,'314159'	,'https://filecoin.io'	,'https://calibration.filscan.io'),
STRUCT('Polis Testnet'	,'Sparta'	,'tPOLIS'	,'333888'	,'333888'	,'https://polis.tech'	,''),
STRUCT('Polis Mainnet'	,'Olympus'	,'POLIS'	,'333999'	,'333999'	,'https://polis.tech'	,''),
STRUCT('Metal C-Chain'	,'Metal'	,'METAL'	,'381931'	,'381931'	,'https://www.metalblockchain.org/'	,'https://metalscan.io'),
STRUCT('Metal Tahoe C-Chain'	,'Metal'	,'METAL'	,'381932'	,'381932'	,'https://www.metalblockchain.org/'	,'https://tahoe.metalscan.io'),
STRUCT('Kekchain'	,'kek'	,'KEK'	,'420420'	,'103090'	,'https://kekchain.com'	,'https://mainnet-explorer.kekchain.com'),
STRUCT('Kekchain (kektest)'	,'kek'	,'tKEK'	,'420666'	,'1'	,'https://kekchain.com'	,'https://testnet-explorer.kekchain.com'),
STRUCT('Arbitrum Rinkeby'	,'ETH'	,'ETH'	,'421611'	,'421611'	,'https://arbitrum.io'	,'https://testnet.arbiscan.io'),
STRUCT('Arbitrum Goerli'	,'ETH'	,'AGOR'	,'421613'	,'421613'	,'https://arbitrum.io/'	,'https://goerli-rollup-explorer.arbitrum.io'),
STRUCT('Dexalot Subnet Testnet'	,'DEXALOT'	,'ALOT'	,'432201'	,'432201'	,'https://dexalot.com'	,'https://subnets-test.avax.network/dexalot'),
STRUCT('Dexalot Subnet'	,'DEXALOT'	,'ALOT'	,'432204'	,'432204'	,'https://dexalot.com'	,'https://subnets.avax.network/dexalot'),
STRUCT('Weelink Testnet'	,'WLK'	,'tWLK'	,'444900'	,'444900'	,'https://weelink.cloud'	,'https://weelink.cloud/#/blockView/overview'),
STRUCT('OpenChain Mainnet'	,'OpenChain'	,'OPC'	,'474142'	,'474142'	,'https://www.openchain.live'	,'https://sidescan.luniverse.io/1641349324562974539'),
STRUCT('CMP-Testnet'	,'CMP'	,'CMP'	,'512512'	,'512512'	,'https://caduceus.foundation/'	,'https://galaxy.scan.caduceus.foundation'),
STRUCT('ethereum Fair'	,'ETF'	,'ETH'	,'513100'	,'1'	,'https://etherfair.org'	,'https://explorer.etherfair.org'),
STRUCT('Scroll'	,'ETH'	,'ETH'	,'534352'	,'534352'	,'https://scroll.io'	,''),
STRUCT('Scroll Goerli Testnet'	,'ETH'	,'ETH'	,'534353'	,'534353'	,'https://scroll.io'	,''),
STRUCT('Scroll Pre-Alpha Testnet'	,'ETH'	,'ETH'	,'534354'	,'534354'	,'https://scroll.io'	,'https://l2scan.scroll.io'),
STRUCT('Vision - Vpioneer Test Chain'	,'Vision-Vpioneer'	,'VS'	,'666666'	,'666666'	,'https://visionscan.org'	,''),
STRUCT('OctaSpace'	,'OCTA'	,'OCTA'	,'800001'	,'800001'	,'https://octa.space'	,'https://explorer.octa.space'),
STRUCT('4GoodNetwork'	,'4GN'	,'APTA'	,'846000'	,'846000'	,'https://bloqs4good.com'	,''),
STRUCT('Vision - Mainnet'	,'Vision'	,'VS'	,'888888'	,'888888'	,'https://www.v.network'	,'https://www.visionscan.org'),
STRUCT('Posichain Mainnet Shard 0'	,'PSC'	,'POSI'	,'900000'	,'900000'	,'https://posichain.org'	,'https://explorer.posichain.org'),
STRUCT('Posichain Testnet Shard 0'	,'PSC'	,'POSI'	,'910000'	,'910000'	,'https://posichain.org'	,'https://explorer-testnet.posichain.org'),
STRUCT('Posichain Devnet Shard 0'	,'PSC'	,'POSI'	,'920000'	,'920000'	,'https://posichain.org'	,'https://explorer-devnet.posichain.org'),
STRUCT('Posichain Devnet Shard 1'	,'PSC'	,'POSI'	,'920001'	,'920001'	,'https://posichain.org'	,'https://explorer-devnet.posichain.org'),
STRUCT('FNCY Testnet'	,'FNCY'	,'FNCY'	,'923018'	,'923018'	,'https://fncyscan-testnet.fncy.world'	,'https://fncyscan-testnet.fncy.world'),
STRUCT('Eluvio Content Fabric'	,'Eluvio'	,'ELV'	,'955305'	,'955305'	,'https://eluv.io'	,'https://explorer.eluv.io'),
STRUCT('Etho Protocol'	,'ETHO'	,'ETHO'	,'1313114'	,'1313114'	,'https://ethoprotocol.com'	,'https://explorer.ethoprotocol.com'),
STRUCT('Xerom'	,'XERO'	,'XERO'	,'1313500'	,'1313500'	,'https://xerom.org'	,''),
STRUCT('Kintsugi'	,'ETH'	,'kiETH'	,'1337702'	,'1337702'	,'https://kintsugi.themerge.dev/'	,'https://explorer.kintsugi.themerge.dev'),
STRUCT('Kiln'	,'ETH'	,'ETH'	,'1337802'	,'1337802'	,'https://kiln.themerge.dev/'	,'https://explorer.kiln.themerge.dev'),
STRUCT('Plian Mainnet Main'	,'Plian'	,'PI'	,'2099156'	,'2099156'	,'https://plian.org/'	,'https://piscan.plian.org/pchain'),
STRUCT('PlatON Dev Testnet Deprecated'	,'PlatON'	,'lat'	,'2203181'	,'1'	,'https://www.platon.network'	,'https://devnetscan.platon.network'),
STRUCT('PlatON Dev Testnet2'	,'PlatON'	,'lat'	,'2206132'	,'1'	,'https://www.platon.network'	,'https://devnet2scan.platon.network'),
STRUCT('Filecoin - Butterfly testnet'	,'FIL'	,'tFIL'	,'3141592'	,'3141592'	,'https://filecoin.io'	,''),
STRUCT('Imversed Mainnet'	,'Imversed'	,'IMV'	,'5555555'	,'5555555'	,'https://imversed.com'	,'https://txe.imversed.network'),
STRUCT('Imversed Testnet'	,'Imversed'	,'IMV'	,'5555558'	,'5555558'	,'https://imversed.com'	,'https://txe-test.imversed.network'),
STRUCT('QL1 Testnet'	,'QOM'	,'QOM'	,'7668378'	,'7668378'	,'https://qom.one'	,'https://testnet.qom.one'),
STRUCT('Musicoin'	,'MUSIC'	,'MUSIC'	,'7762959'	,'7762959'	,'https://musicoin.tw'	,''),
STRUCT('Plian Mainnet Subchain 1'	,'Plian'	,'PI'	,'8007736'	,'8007736'	,'https://plian.org'	,'https://piscan.plian.org/child_0'),
STRUCT('Plian Testnet Subchain 1'	,'Plian'	,'TPI'	,'10067275'	,'10067275'	,'https://plian.org/'	,'https://testnet.plian.org/child_test'),
STRUCT('Sepolia'	,'ETH'	,'SEP'	,'11155111'	,'11155111'	,'https://sepolia.otterscan.io'	,'https://sepolia.etherscan.io'),
STRUCT('PepChain Churchill'	,'PEP'	,'TPEP'	,'13371337'	,'13371337'	,'https://pepchain.io'	,''),
STRUCT('Plian Testnet Main'	,'Plian'	,'TPI'	,'16658437'	,'16658437'	,'https://plian.org'	,'https://testnet.plian.org/testnet'),
STRUCT('IOLite'	,'ILT'	,'ILT'	,'18289463'	,'18289463'	,'https://iolite.io'	,''),
STRUCT('SmartMesh Mainnet'	,'Spectrum'	,'SMT'	,'20180430'	,'1'	,'https://smartmesh.io'	,'https://spectrum.pub'),
STRUCT('quarkblockchain'	,'QKI'	,'QKI'	,'20181205'	,'20181205'	,'https://quarkblockchain.org/'	,''),
STRUCT('Excelon Mainnet'	,'XLON'	,'xlon'	,'22052002'	,'22052002'	,'https://xlon.org'	,'https://explorer.excelon.io'),
STRUCT('Excoincial Chain Volta-Testnet'	,'TEXL'	,'TEXL'	,'27082017'	,'27082017'	,''	,'https://testnet-explorer.exlscan.com'),
STRUCT('Excoincial Chain Mainnet'	,'EXL'	,'EXL'	,'27082022'	,'27082022'	,''	,'https://exlscan.com'),
STRUCT('Auxilium Network Mainnet'	,'AUX'	,'AUX'	,'28945486'	,'28945486'	,'https://auxilium.global'	,''),
STRUCT('Filecoin - Local testnet'	,'FIL'	,'tFIL'	,'31415926'	,'31415926'	,'https://filecoin.io'	,''),
STRUCT('Joys Digital Mainnet'	,'JOYS'	,'JOYS'	,'35855456'	,'35855456'	,'https://joys.digital'	,''),
STRUCT('Aquachain'	,'AQUA'	,'AQUA'	,'61717561'	,'61717561'	,'https://aquachain.github.io'	,''),
STRUCT('Joys Digital TestNet'	,'TOYS'	,'TOYS'	,'99415706'	,'99415706'	,'https://joys.digital'	,''),
STRUCT('Gather Mainnet Network'	,'GTH'	,'GTH'	,'192837465'	,'192837465'	,'https://gather.network'	,'https://explorer.gather.network'),
STRUCT('Neon EVM DevNet'	,'Solana'	,'NEON'	,'245022926'	,'245022926'	,'https://neon-labs.org'	,'https://devnet.explorer.neon-labs.org'),
STRUCT('Neon EVM MainNet'	,'Solana'	,'NEON'	,'245022934'	,'245022934'	,'https://neon-labs.org'	,'https://mainnet.explorer.neon-labs.org'),
STRUCT('Neon EVM TestNet'	,'Solana'	,'NEON'	,'245022940'	,'245022940'	,'https://neon-labs.org'	,'https://testnet.explorer.neon-labs.org'),
STRUCT('OneLedger Mainnet'	,'OLT'	,'OLT'	,'311752642'	,'311752642'	,'https://oneledger.io'	,'https://mainnet-explorer.oneledger.network'),
STRUCT('Calypso NFT Hub (SKALE Testnet)'	,'staging-utter-unripe-menkar'	,'sFUEL'	,'344106930'	,'344106930'	,'https://calypsohub.network/'	,'https://staging-utter-unripe-menkar.explorer.staging-v3.skalenodes.com'),
STRUCT('Gather Testnet Network'	,'GTH'	,'GTH'	,'356256156'	,'356256156'	,'https://gather.network'	,'https://testnet-explorer.gather.network'),
STRUCT('Gather Devnet Network'	,'GTH'	,'GTH'	,'486217935'	,'486217935'	,'https://gather.network'	,'https://devnet-explorer.gather.network'),
STRUCT('Nebula Staging'	,'staging-faint-slimy-achird'	,'sFUEL'	,'503129905'	,'503129905'	,'https://nebulachain.io/'	,'https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com'),
STRUCT('IPOS Network'	,'IPOS'	,'IPOS'	,'1122334455'	,'1122334455'	,'https://iposlab.com'	,''),
STRUCT('Aurora Mainnet'	,'NEAR'	,'ETH'	,'1313161554'	,'1313161554'	,'https://aurora.dev'	,'https://aurorascan.dev'),
STRUCT('Aurora Testnet'	,'NEAR'	,'ETH'	,'1313161555'	,'1313161555'	,'https://aurora.dev'	,'https://testnet.aurorascan.dev'),
STRUCT('Aurora Betanet'	,'NEAR'	,'ETH'	,'1313161556'	,'1313161556'	,'https://aurora.dev'	,''),
STRUCT('Nebula Mainnet'	,'green-giddy-denebola'	,'sFUEL'	,'1482601649'	,'1482601649'	,'https://nebulachain.io/'	,'https://green-giddy-denebola.explorer.mainnet.skalenodes.com'),
STRUCT('Calypso NFT Hub (SKALE)'	,'honorable-steel-rasalhague'	,'sFUEL'	,'1564830818'	,'1564830818'	,'https://calypsohub.network/'	,'https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com'),
STRUCT('Harmony Mainnet Shard 0'	,'Harmony'	,'ONE'	,'1666600000'	,'1666600000'	,'https://www.harmony.one/'	,'https://explorer.harmony.one'),
STRUCT('Harmony Mainnet Shard 1'	,'Harmony'	,'ONE'	,'1666600001'	,'1666600001'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Mainnet Shard 2'	,'Harmony'	,'ONE'	,'1666600002'	,'1666600002'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Mainnet Shard 3'	,'Harmony'	,'ONE'	,'1666600003'	,'1666600003'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Testnet Shard 0'	,'Harmony'	,'ONE'	,'1666700000'	,'1666700000'	,'https://www.harmony.one/'	,'https://explorer.pops.one'),
STRUCT('Harmony Testnet Shard 1'	,'Harmony'	,'ONE'	,'1666700001'	,'1666700001'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Testnet Shard 2'	,'Harmony'	,'ONE'	,'1666700002'	,'1666700002'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Testnet Shard 3'	,'Harmony'	,'ONE'	,'1666700003'	,'1666700003'	,'https://www.harmony.one/'	,''),
STRUCT('Harmony Devnet Shard 0'	,'Harmony'	,'ONE'	,'1666900000'	,'1666900000'	,'https://www.harmony.one/'	,'https://explorer.ps.hmny.io'),
STRUCT('DataHopper'	,'HOP'	,'HOP'	,'2021121117'	,'2021121117'	,'https://www.DataHopper.com'	,''),
STRUCT('Pirl'	,'PIRL'	,'PIRL'	,'3125659152'	,'3125659152'	,'https://pirl.io'	,''),
STRUCT('OneLedger Testnet Frankenstein'	,'OLT'	,'OLT'	,'4216137055'	,'4216137055'	,'https://oneledger.io'	,'https://frankenstein-explorer.oneledger.network'),
STRUCT('Palm Testnet'	,'Palm'	,'PALM'	,'11297108099'	,'11297108099'	,'https://palm.io'	,'https://explorer.palm-uat.xyz'),
STRUCT('Palm'	,'Palm'	,'PALM'	,'11297108109'	,'11297108109'	,'https://palm.io'	,'https://explorer.palm.io'),
STRUCT('Ntity Mainnet'	,'Ntity'	,'NTT'	,'197710212030'	,'197710212030'	,'https://ntity.io'	,'https://blockscout.ntity.io'),
STRUCT('Haradev Testnet'	,'Ntity'	,'NTTH'	,'197710212031'	,'197710212031'	,'https://ntity.io'	,'https://blockscout.haradev.com'),
STRUCT('Molereum Network'	,'ETH'	,'MOLE'	,'6022140761023'	,'6022140761023'	,'https://github.com/Jdubedition/molereum'	,''),
STRUCT('Godwoken Testnet (V1)'	,'GWT'	,'CKB'	,'868455272153094'	,'868455272153094'	,'https://www.nervos.org'	,'https://v1.aggron.gwscan.com')])